### ISSUE TITLE
Validation doesn't work while updating Pets and Owners on Tomcat 8

### ISSUE THREAD

**Issue by trepel** [spring-projects/spring-petclinic#100]
For instance, trying to change Owner's telephone number to some invalid value you get `HTTP Status 405 - JSPs only permit GET POST or HEAD`. Root cause for this is that JSP 2.3 doesn't support HTTP PUT method anymore. On Tomcat 7 everything works as expected, because it uses older version of JSP.

I created pull request for this with suggested solution:
https://github.com/spring-projects/spring-petclinic/pull/99

**Comment by arey** [comment]
Using both the ```HiddenHttpMethodFilter```and the Spring tag ```<form:form method="${method}"```, an hidden input field is generated: ```<input type="hidden" name="_method" value="put">```. Thus the browser send a POST request wether the user edit or create a new pet owner.

The ```HiddenHttpMethodFilter``` wraps the original request into a ```HttpMethodRequestWrapper```. Tomcat see a PUT method. 

This behavior changes in Tomcat 8 is described into this issue: https://bz.apache.org/bugzilla/show_bug.cgi?id=56568

Thaere is no workaround:
* Using  ```%@page isErrorPage="true"%>```: no CSS / JS are loaded
* Using the PATCH verb: do not change anything
* Using the ```AnyMethodHttpJspBase``` class creates a link between the petclinic war and the application server

@michaelisvy what do you think about the #99 pull request?

**Comment by msuganthan** [comment]
http://stackoverflow.com/questions/13629653/using-put-and-delete-methods-in-spring-mvc

**Comment by arey** [comment]
@msuganthan the Spring ```<form:form>```tag already add a "_method" hidden input field.

**Comment by michaelisvy** [comment]
@arey I think we should accept it.

**Comment by arey** [comment]
Merge has been accepted. Thanks @trepel
