### ISSUE TITLE
Compile error in PetClinicIntegrationTests

### ISSUE THREAD

**Issue by rmorrise** [spring-projects/spring-petclinic#1001]
https://github.com/spring-projects/spring-petclinic/blob/4f3cbaa9aa25402cf98fa22fd100e39155ba23ae/src/test/java/org/springframework/samples/petclinic/PetClinicIntegrationTests.java#L25

Should be:
```import org.springframework.boot.web.server.LocalServerPort;```

**Comment by dsyer** [comment]
That other one is "deprecated since 2.7.0 for removal in 3.0.0" (per the java docs). I think we are fine.
