### ISSUE TITLE
usbstick/sls-demo.box is 404

### ISSUE THREAD

**Issue by r1ddl3m37h15** [spring-projects/spring-petclinic#102]
C:\Users\Jeff\share\spring-petclinic>vagrant box add usbstick/sls-demo.box --name sls-demo
The box 'usbstick/sls-demo.box' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/usbstick/sls-demo.box"]
Error: The requested URL returned error: 404 Not Found

C:\Users\Jeff\share\spring-petclinic>

**Comment by michaelisvy** [comment]
Closing, it seems like a mistake.
