### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by Aj7Ay** [spring-projects/spring-petclinic#1037]
while commit sir
target folder is added to .gitignore file and we can't get target follder and we cant create a new jar file for that .
please remove and upload springboot petclinic 
thanks sir

**Comment by dsyer** [comment]
The `target` folder is generated by the build (using Maven). It is included in `.gitignore` intentionally. Are you trying to create a directory called `target` manually somewhere? If so why?

**Comment by Aj7Ay** [comment]
I was learning Aws devops and used for training purposes and getting error
