### ISSUE TITLE
compile error due to incompatible dependency version

### ISSUE THREAD

**Issue by gerardorosiles** [spring-projects/spring-petclinic#1044]
I get the following error
`[ERROR] Failed to execute goal io.spring.javaformat:spring-javaformat-maven-plugin:0.0.31:validate (default) on project spring-petclinic: Execution default of goal io.spring.javaformat:spring-javaformat-maven-plugin:0.0.31:validate failed: An API incompatibility was encountered while executing io.spring.javaformat:spring-javaformat-maven-plugin:0.0.31:validate: java.lang.UnsupportedClassVersionError: io/spring/javaformat/eclipse/jdt/jdk11/internal/formatter/DefaultCodeFormatter has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
`

the most recent plugin version for which I can compile/package is 0.0.29

I am using and Amazon Linux 2 instance with
openjdk version "1.8.0_332"
OpenJDK Runtime Environment (build 1.8.0_332-b09)

**Comment by dubograev** [comment]
I can see the same error

**Comment by dsyer** [comment]
The README explains that you need to use Java 11 or newer. Did you try that? Spring 6 is on the horizon and this project will switch to Java 17 at that point.

**Comment by gerardorosiles** [comment]
I just went with the pom file, and have java 8 as a requirement.
pom.xml file still specifies:
    
    <java.version>1.8</java.version>

that lea
And not everybody has the luxury of controlling the Java version.

**Comment by dsyer** [comment]
Fixed in 70f615a
