### ISSUE TITLE
Question about benchmarks

### ISSUE THREAD

**Issue by ShimchenkoMarina** [spring-projects/spring-petclinic#1046]
Hi, it is not an issue but rather a question. I am not familiar with this application, but looking for latency-oriented benchmarks. 
Latency-oriented BMs usually focus on response time to a user. Is it the case here? Looking forward to your explanation. Thanks in advance.

**Comment by dsyer** [comment]
We don't publish latency benchmarks for PetClinic, so I don't really know what you are asking.
