### ISSUE TITLE
Not able to get any data

### ISSUE THREAD

**Issue by venkatad** [spring-projects/spring-petclinic#1087]
using Spring petclinic-microservices and spring-petclinic-angular version (NOT angularJS) Able to run successfully angular version and
able to run different servers in microservices projects. but I am not able to connect to backend. I am NOT using docker version, just using ../mvnw spring-boot:run command in every project (admin, config server, discovery, vets, pets, customer etc)

**Comment by dsyer** [comment]
That project is in a different repo with its own issue tracker: https://github.com/spring-petclinic/spring-petclinic-microservices.
