### ISSUE TITLE
HTTP 400 error if editing pets with invalid date instead of 'invalid date' message

### ISSUE THREAD

**Issue by trepel** [spring-projects/spring-petclinic#110]
If you try to edit pet's birth name with some invalid value (e.g. 2012/09/44), the HTTP Status 400 error page is shown instead of displaying nice 'invalid date' message in edit pet form.

This error is caused by https://github.com/spring-projects/spring-petclinic/commit/3bcf84543ec586173731942a83178eed561f7d3a

**Comment by arey** [comment]
I've confirmes the bug is cause by 3bcf845

**Comment by arey** [comment]
The ```BindingResult``` parameter should be follow the parameter annoyed with```@Valid```
