### ISSUE TITLE
Setting dates doesn't work properly - they are shifted by one day

### ISSUE THREAD

**Issue by trepel** [spring-projects/spring-petclinic#111]
Hi, when editing/storing entities with dates, the dates are shifted by one day back. I am not sure if you will be able to reproduce this. I came across similar issue in project using JSF and it was caused by TimeZone settings. My timezone is CET.

**Comment by arey** [comment]
I've got the same behavior with GMT+1 timezone

**Comment by michaelisvy** [comment]
hi @trepel , we are discussing about the new features we would like to have inside Petclinic. Since you have done quite a few pull requests, would you like to be involved? 
We were not sure how to contact you. If you'd like you can email me directly on misvy at pivotal dot io.

Michael.
