### ISSUE TITLE
Error Build 

### ISSUE THREAD

**Issue by hendisantika** [spring-projects/spring-petclinic#123]
Downloaded: https://repo.maven.apache.org/maven2/com/rometools/rome-parent/1.5.0
/rome-parent-1.5.0.pom (6 KB at 13.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/rometools/rome-utils/1.5.0
/rome-utils-1.5.0.pom
Downloaded: https://repo.maven.apache.org/maven2/com/rometools/rome-utils/1.5.0/
rome-utils-1.5.0.pom (2 KB at 4.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/jdom/jdom/2.0.2/jdom-2.0.2
.pom
Downloaded: https://repo.maven.apache.org/maven2/org/jdom/jdom/2.0.2/jdom-2.0.2.
pom (5 KB at 8.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/joda-time/joda-time-jsptags/1.
1.1/joda-time-jsptags-1.1.1.pom
Downloaded: https://repo.maven.apache.org/maven2/joda-time/joda-time-jsptags/1.1
.1/joda-time-jsptags-1.1.1.pom (12 KB at 13.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/hibernate/hibernate-entity
manager/4.3.6.Final/hibernate-entitymanager-4.3.6.Final.pom
Downloaded: https://repo.maven.apache.org/maven2/org/hibernate/hibernate-entitym
anager/4.3.6.Final/hibernate-entitymanager-4.3.6.Final.pom (4 KB at 7.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/javax/validation/validation-ap
i/1.0.0.GA/validation-api-1.0.0.GA.pom
Downloaded: https://repo.maven.apache.org/maven2/javax/validation/validation-api
/1.0.0.GA/validation-api-1.0.0.GA.pom (5 KB at 9.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/hibernate/hibernate-ehcach
e/4.3.6.Final/hibernate-ehcache-4.3.6.Final.pom
Downloaded: https://repo.maven.apache.org/maven2/org/hibernate/hibernate-ehcache
/4.3.6.Final/hibernate-ehcache-4.3.6.Final.pom (3 KB at 4.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/net/sf/ehcache/ehcache-core/2.
4.3/ehcache-core-2.4.3.pom
Downloaded: https://repo.maven.apache.org/maven2/net/sf/ehcache/ehcache-core/2.4
.3/ehcache-core-2.4.3.pom (35 KB at 30.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/net/sf/ehcache/ehcache-parent/
2.2/ehcache-parent-2.2.pom
Downloaded: https://repo.maven.apache.org/maven2/net/sf/ehcache/ehcache-parent/2
.2/ehcache-parent-2.2.pom (20 KB at 34.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/net/sf/ehcache/ehcache-core/2.
6.9/ehcache-core-2.6.9.pom
Downloaded: https://repo.maven.apache.org/maven2/net/sf/ehcache/ehcache-core/2.6
.9/ehcache-core-2.6.9.pom (30 KB at 45.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/net/sf/ehcache/ehcache-parent/
2.5/ehcache-parent-2.5.pom
Downloaded: https://repo.maven.apache.org/maven2/net/sf/ehcache/ehcache-parent/2
.5/ehcache-parent-2.5.pom (16 KB at 27.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/webjars/bootstrap/2.3.0/bo
otstrap-2.3.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/webjars/bootstrap/2.3.0/boo
tstrap-2.3.0.pom (6 KB at 11.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/webjars/jquery/1.9.0/jquer
y-1.9.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/webjars/jquery/1.9.0/jquery
-1.9.0.pom (4 KB at 7.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/webjars/jquery-ui/1.10.3/j
query-ui-1.10.3.pom
Downloaded: https://repo.maven.apache.org/maven2/org/webjars/jquery-ui/1.10.3/jq
uery-ui-1.10.3.pom (6 KB at 11.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/webjars/jquery/1.9.1/jquer
y-1.9.1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/webjars/jquery/1.9.1/jquery
-1.9.1.pom (4 KB at 8.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/webjars/jquery/2.0.3-1/jqu
ery-2.0.3-1.pom
Downloaded: https://repo.maven.apache.org/maven2/org/webjars/jquery/2.0.3-1/jque
ry-2.0.3-1.pom (5 KB at 9.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/webjars/angular-ui-bootstr
ap/0.12.0/angular-ui-bootstrap-0.12.0.pom
Downloaded: https://repo.maven.apache.org/maven2/org/webjars/angular-ui-bootstra
p/0.12.0/angular-ui-bootstrap-0.12.0.pom (7 KB at 13.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/springframework/spring-tes
t/4.1.1.RELEASE/spring-test-4.1.1.RELEASE.pom
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/spring-test
/4.1.1.RELEASE/spring-test-4.1.1.RELEASE.pom (7 KB at 14.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/datatable
s-jsp/0.10.1/datatables-jsp-0.10.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/datatables
-jsp/0.10.1/datatables-jsp-0.10.1.pom (5 KB at 9.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/dandelion
-datatables/0.10.1/dandelion-datatables-0.10.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/dandelion-
datatables/0.10.1/dandelion-datatables-0.10.1.pom (18 KB at 32.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/datatable
s-core/0.10.1/datatables-core-0.10.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/datatables
-core/0.10.1/datatables-core-0.10.1.pom (3 KB at 5.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/dandelion
-core/0.10.1/dandelion-core-0.10.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/dandelion-
core/0.10.1/dandelion-core-0.10.1.pom (2 KB at 3.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/dandelion
/0.10.1/dandelion-0.10.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/dandelion/
0.10.1/dandelion-0.10.1.pom (14 KB at 25.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jac
kson-core/2.3.1/jackson-core-2.3.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jack
son-core/2.3.1/jackson-core-2.3.1.pom (6 KB at 12.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jac
kson-annotations/2.3.1/jackson-annotations-2.3.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jack
son-annotations/2.3.1/jackson-annotations-2.3.1.pom (2 KB at 4.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jac
kson-databind/2.3.1/jackson-databind-2.3.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jack
son-databind/2.3.1/jackson-databind-2.3.1.pom (6 KB at 12.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/googlecode/json-simple/jso
n-simple/1.1.1/json-simple-1.1.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/googlecode/json-simple/json
-simple/1.1.1/json-simple-1.1.1.pom (4 KB at 7.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/dandelion
-jsp/0.10.1/dandelion-jsp-0.10.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/dandelion-
jsp/0.10.1/dandelion-jsp-0.10.1.pom (3 KB at 6.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/datatable
s-export-itext/0.10.1/datatables-export-itext-0.10.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/datatables
-export-itext/0.10.1/datatables-export-itext-0.10.1.pom (2 KB at 2.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/datatable
s-extras/0.10.1/datatables-extras-0.10.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/datatables
-extras/0.10.1/datatables-extras-0.10.1.pom (856 B at 2.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/itextpdf/itextpdf/5.4.5/it
extpdf-5.4.5.pom
Downloaded: https://repo.maven.apache.org/maven2/com/itextpdf/itextpdf/5.4.5/ite
xtpdf-5.4.5.pom (9 KB at 13.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/itextpdf/itext-parent/1.0.
0/itext-parent-1.0.0.pom
Downloaded: https://repo.maven.apache.org/maven2/com/itextpdf/itext-parent/1.0.0
/itext-parent-1.0.0.pom (4 KB at 8.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/datatype
/jackson-datatype-joda/2.3.1/jackson-datatype-joda-2.3.1.pom
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/datatype/
jackson-datatype-joda/2.3.1/jackson-datatype-joda-2.3.1.pom (4 KB at 7.5 KB/sec)

Downloading: https://repo.maven.apache.org/maven2/joda-time/joda-time/2.1/joda-t
ime-2.1.pom
Downloaded: https://repo.maven.apache.org/maven2/joda-time/joda-time/2.1/joda-ti
me-2.1.pom (16 KB at 27.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/javax/servlet/jsp/jstl/jstl-ap
i/1.2/jstl-api-1.2.jar
Downloading: https://repo.maven.apache.org/maven2/javax/xml/bind/jaxb-api/2.2.7/
jaxb-api-2.2.7.jar
Downloading: https://repo.maven.apache.org/maven2/com/sun/xml/bind/jaxb-core/2.2
.7/jaxb-core-2.2.7.jar
Downloading: https://repo.maven.apache.org/maven2/com/sun/xml/bind/jaxb-impl/2.2
.7/jaxb-impl-2.2.7.jar
Downloading: https://repo.maven.apache.org/maven2/com/sun/istack/istack-commons-
runtime/2.16/istack-commons-runtime-2.16.jar
Downloaded: https://repo.maven.apache.org/maven2/javax/servlet/jsp/jstl/jstl-api
/1.2/jstl-api-1.2.jar (30 KB at 16.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/sun/xml/fastinfoset/FastIn
foset/1.2.12/FastInfoset-1.2.12.jar
Downloaded: https://repo.maven.apache.org/maven2/com/sun/istack/istack-commons-r
untime/2.16/istack-commons-runtime-2.16.jar (23 KB at 5.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/javax/xml/bind/jsr173_api/1.0/
jsr173_api-1.0.jar
Downloaded: https://repo.maven.apache.org/maven2/javax/xml/bind/jaxb-api/2.2.7/j
axb-api-2.2.7.jar (98 KB at 16.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/springframework/spring-oxm
/4.1.1.RELEASE/spring-oxm-4.1.1.RELEASE.jar
Downloaded: https://repo.maven.apache.org/maven2/javax/xml/bind/jsr173_api/1.0/j
sr173_api-1.0.jar (49 KB at 7.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/springframework/spring-jms
/4.1.1.RELEASE/spring-jms-4.1.1.RELEASE.jar
Downloaded: https://repo.maven.apache.org/maven2/com/sun/xml/fastinfoset/FastInf
oset/1.2.12/FastInfoset-1.2.12.jar (287 KB at 32.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/springframework/spring-mes
saging/4.1.1.RELEASE/spring-messaging-4.1.1.RELEASE.jar
Downloaded: https://repo.maven.apache.org/maven2/com/sun/xml/bind/jaxb-core/2.2.
7/jaxb-core-2.2.7.jar (217 KB at 17.3 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/rometools/rome/1.5.0/rome-
1.5.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/spring-mess
aging/4.1.1.RELEASE/spring-messaging-4.1.1.RELEASE.jar (281 KB at 18.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/rometools/rome-utils/1.5.0
/rome-utils-1.5.0.jar
Downloaded: https://repo.maven.apache.org/maven2/com/rometools/rome-utils/1.5.0/
rome-utils-1.5.0.jar (7 KB at 0.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/jdom/jdom/2.0.2/jdom-2.0.2
.jar
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/spring-oxm/
4.1.1.RELEASE/spring-oxm-4.1.1.RELEASE.jar (81 KB at 4.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/joda-time/joda-time-jsptags/1.
1.1/joda-time-jsptags-1.1.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/springframework/spring-jms/
4.1.1.RELEASE/spring-jms-4.1.1.RELEASE.jar (261 KB at 15.0 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/hibernate/hibernate-entity
manager/4.3.6.Final/hibernate-entitymanager-4.3.6.Final.jar
Downloaded: https://repo.maven.apache.org/maven2/joda-time/joda-time-jsptags/1.1
.1/joda-time-jsptags-1.1.1.jar (34 KB at 1.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/javax/validation/validation-ap
i/1.0.0.GA/validation-api-1.0.0.GA.jar
Downloaded: https://repo.maven.apache.org/maven2/org/jdom/jdom/2.0.2/jdom-2.0.2.
jar (289 KB at 12.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/hibernate/hibernate-ehcach
e/4.3.6.Final/hibernate-ehcache-4.3.6.Final.jar
Downloaded: https://repo.maven.apache.org/maven2/com/rometools/rome/1.5.0/rome-1
.5.0.jar (239 KB at 10.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/net/sf/ehcache/ehcache-core/2.
6.9/ehcache-core-2.6.9.jar
Downloaded: https://repo.maven.apache.org/maven2/javax/validation/validation-api
/1.0.0.GA/validation-api-1.0.0.GA.jar (47 KB at 1.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/webjars/bootstrap/2.3.0/bo
otstrap-2.3.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/hibernate/hibernate-ehcache
/4.3.6.Final/hibernate-ehcache-4.3.6.Final.jar (133 KB at 5.2 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/webjars/jquery-ui/1.10.3/j
query-ui-1.10.3.jar
Downloaded: https://repo.maven.apache.org/maven2/org/webjars/bootstrap/2.3.0/boo
tstrap-2.3.0.jar (138 KB at 3.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/webjars/jquery/2.0.3-1/jqu
ery-2.0.3-1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/hibernate/hibernate-entitym
anager/4.3.6.Final/hibernate-entitymanager-4.3.6.Final.jar (632 KB at 15.2 KB/se
c)
Downloading: https://repo.maven.apache.org/maven2/org/webjars/angular-ui-bootstr
ap/0.12.0/angular-ui-bootstrap-0.12.0.jar
Downloaded: https://repo.maven.apache.org/maven2/org/webjars/jquery-ui/1.10.3/jq
uery-ui-1.10.3.jar (605 KB at 13.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/org/webjars/angularjs/1.2.16-2
/angularjs-1.2.16-2.jar
Downloaded: https://repo.maven.apache.org/maven2/org/webjars/jquery/2.0.3-1/jque
ry-2.0.3-1.jar (152 KB at 3.4 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/datatable
s-jsp/0.10.1/datatables-jsp-0.10.1.jar
Downloaded: https://repo.maven.apache.org/maven2/org/webjars/angular-ui-bootstra
p/0.12.0/angular-ui-bootstrap-0.12.0.jar (96 KB at 2.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/datatable
s-core/0.10.1/datatables-core-0.10.1.jar
Downloaded: https://repo.maven.apache.org/maven2/com/sun/xml/bind/jaxb-impl/2.2.
7/jaxb-impl-2.2.7.jar (899 KB at 18.8 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/dandelion
-core/0.10.1/dandelion-core-0.10.1.jar
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/datatables
-jsp/0.10.1/datatables-jsp-0.10.1.jar (44 KB at 0.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/googlecode/json-simple/jso
n-simple/1.1.1/json-simple-1.1.1.jar
Downloaded: https://repo.maven.apache.org/maven2/com/googlecode/json-simple/json
-simple/1.1.1/json-simple-1.1.1.jar (24 KB at 0.5 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/dandelion
-jsp/0.10.1/dandelion-jsp-0.10.1.jar
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/dandelion-
jsp/0.10.1/dandelion-jsp-0.10.1.jar (6 KB at 0.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/github/dandelion/datatable
s-export-itext/0.10.1/datatables-export-itext-0.10.1.jar
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/datatables
-core/0.10.1/datatables-core-0.10.1.jar (319 KB at 5.9 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/itextpdf/itextpdf/5.4.5/it
extpdf-5.4.5.jar
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/datatables
-export-itext/0.10.1/datatables-export-itext-0.10.1.jar (6 KB at 0.1 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jac
kson-core/2.3.1/jackson-core-2.3.1.jar
Downloaded: https://repo.maven.apache.org/maven2/com/github/dandelion/dandelion-
core/0.10.1/dandelion-core-0.10.1.jar (263 KB at 4.6 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jac
kson-databind/2.3.1/jackson-databind-2.3.1.jar
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jack
son-core/2.3.1/jackson-core-2.3.1.jar (194 KB at 2.7 KB/sec)
Downloading: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/datatype
/jackson-datatype-joda/2.3.1/jackson-datatype-joda-2.3.1.jar
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/datatype/
jackson-datatype-joda/2.3.1/jackson-datatype-joda-2.3.1.jar (44 KB at 0.6 KB/sec
)
Downloaded: https://repo.maven.apache.org/maven2/com/fasterxml/jackson/core/jack
son-databind/2.3.1/jackson-databind-2.3.1.jar (893 KB at 10.4 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/net/sf/ehcache/ehcache-core/2.6
.9/ehcache-core-2.6.9.jar (1316 KB at 10.6 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/webjars/angularjs/1.2.16-2/
angularjs-1.2.16-2.jar (1753 KB at 6.3 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:09 min
[INFO] Finished at: 2015-12-23T07:31:01+07:00
[INFO] Final Memory: 12M/169M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project spring-petclinic: Could not resolve de
pendencies for project org.springframework.samples:spring-petclinic:war:1.0.0-SN
APSHOT: Could not transfer artifact com.itextpdf:itextpdf:jar:5.4.5 from/to cent
ral (https://repo.maven.apache.org/maven2): GET request of: com/itextpdf/itextpd
f/5.4.5/itextpdf-5.4.5.jar from central failed: SSL peer shut down incorrectly -
> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyReso
lutionException

=================================
How do I handle this?
Thankss

**Comment by michaelisvy** [comment]
The file is available here:
https://repo1.maven.org/maven2/com/itextpdf/itextpdf/5.4.5/

Isn't it just your internet connection that is having issues?

**Comment by arey** [comment]
No news so I close this issue.
