### ISSUE TITLE
Petclinic cloudfoundry link is broken.

### ISSUE THREAD

**Issue by colinbut** [spring-projects/spring-petclinic#126]
A very minor thing i noticed...

The link to the app in Cloudfoundry on the [home petclinic](https://github.com/spring-projects/spring-petclinic/wiki/home-petclinic) wiki page doesn't work. 

[ http://spring-petclinic.cloudfoundry.com/](http://spring-petclinic.cloudfoundry.com/)

It is giving me 404 not found.

If it's not hosted on there anymore, perhaps update that bit on that wiki page.?

**Comment by wsh17** [comment]
I have see the same issue, it works on the STS Spring Tool TC server on a localhost, but deployed to cloud foundry I can not get to the URL.  I even went to apps manager and tried to map it to a new url which did not work.

**Comment by KumareshBabuNS** [comment]
Hi @colinbut ,
Create a route and hostname for spring-petclinic app in your apps manager console. 
For route, check it your console and give hostname as spring-petclinic. It will work!!!!

**Comment by dsyer** [comment]
I deleted the wiki (it duplicated the README anyway).

**Comment by KidPluto** [comment]
> Create a route and hostname for spring-petclinic app in your apps manager console.

Can someone give me a little more detail?  Thx

**Comment by dsyer** [comment]
https://docs.cloudfoundry.org/devguide/deploy-apps/routes-domains.html
