### ISSUE TITLE
Null Pointer Exception on Pet Controller

### ISSUE THREAD

**Issue by 4313testing** [spring-projects/spring-petclinic#1272]
Null Pointer Exception on Pet Controller when Owner_ID is Wrong 

![image](https://github.com/spring-projects/spring-petclinic/assets/135747487/b6d3a5d2-d1dc-4a66-9a0a-2848ff0eb22e)

We need to add Validation for Owner_ID to handle the error when its not Found and Avoid Null Pointer Exception

**Comment by dsyer** [comment]
There shouldn't be any path in the UI to this endpoint with a non-existent owner. I can see what you mean, but the error will never be seen in practice, unless people are typing or bookmarking invalid URLs in the browser.

**Comment by 4313testing** [comment]
It is still important to handle such cases in the code. While it may not be a practical scenario for users to encounter invalid URLs by typing or bookmarking, it's good practice to implement proper error handling and validation mechanisms to ensure the robustness and security of the application.

**Comment by 4313testing** [comment]
it can be updated this simple way with execption handling i suggest 
![image](https://github.com/spring-projects/spring-petclinic/assets/135747487/e1c0ef6e-d3be-4299-b130-b9e3807180cf)

**Comment by 4313testing** [comment]
@dsyer please confirm if possible

**Comment by dsyer** [comment]
I confirm that there is no defensive null detection for suicidal users. I don’t know if I think it’s a problem or not. On balance, given the aims of this project, I’m guessing not.

**Comment by 4313testing** [comment]
> I confirm that there is no defensive null detection for suicidal users. I don’t know if I think it’s a problem or not. On balance, given the aims of this project, I’m guessing not.

i understand your point of view but and its always better to cover the code for potential issue .
I already added a solution for that so is it possible to accept my solution ?

**Comment by dsyer** [comment]
For reference the solution was #1278. I closed it because it was doing too much (IMO) but a simpler approach night work, just using normal `IllegalArgumentException`.

**Comment by 4313testing** [comment]
okay i did a simpler solution 
you can find it on this new PR #1293

**Comment by 4313testing** [comment]
@dsyer you did not accepted this PR #1293 
So in this case can i do another solution ?

**Comment by dsyer** [comment]
Sorry, I re-opened it.

**Comment by 4313testing** [comment]
Sorry i had some issue on that previous PR 
please check the new PR #1294
