### ISSUE TITLE
XSS Vulnerability in Add Owner Form

### ISSUE THREAD

**Issue by 4313testing** [spring-projects/spring-petclinic#1273]
![image](https://github.com/spring-projects/spring-petclinic/assets/135747487/77353be6-2856-444d-aeeb-fbd35af82dc3)

in Add/Update Form for Owner there is XSS Vulnerability which is not handled

**Comment by 4313testing** [comment]
@dsyer please confirm if possible

**Comment by dsyer** [comment]
Would you like to suggest a fix? I haven’t tried it so I can’t really comment otherwise.

**Comment by 4313testing** [comment]
> Would you like to suggest a fix? I haven’t tried it so I can’t really comment otherwise.

Yes of course i have the solution

**Comment by dsyer** [comment]
I just tried it and it escapes the HTML you show, so there is no XSS. I don't know how to reproduce, so I think I'll close this, but please comment if you think I am wrong.

**Comment by 4313testing** [comment]
@dsyer please check again try to do it in Address Input 
![Uploading xssBug.png…]()

**Comment by 4313testing** [comment]
@dsyer please check again try to do it in Address Input 
![xssBug](https://github.com/spring-projects/spring-petclinic/assets/135747487/4a3b0a4e-d451-4deb-b107-d82bb5f910f8)

**Comment by 4313testing** [comment]
this is the Solution i suggest 
![image](https://github.com/spring-projects/spring-petclinic/assets/135747487/94d6fe44-0a8a-4b85-b3d3-b73c0795a28b)

**Comment by dsyer** [comment]
But there is no XSS attack is there - the HTML is never rendered and the alert never appears in the browser? Your solution is just double-encoding (once in the controller and once again in the view renderer).
