### ISSUE TITLE
Invalid Date Year for pet Birthdate Input

### ISSUE THREAD

**Issue by 4313testing** [spring-projects/spring-petclinic#1282]
we can input a non existing Year for Birthdate for Pet for example if we put 01/01/2030 in Add or Edit Pet Form it will pass which is wrong 
![image](https://github.com/spring-projects/spring-petclinic/assets/135747487/565181fd-33aa-4832-9f64-b2c5cfc5c49c)

**Comment by dsyer** [comment]
I don't think this application is sophisticated enough to catch that kind of error. It hardly seems worth it, but if you have a neat solution (not too much code), I'd be happy to see it.

**Comment by arsh1598** [comment]
Can I work on it?

**Comment by dsyer** [comment]
Of course. But not too much code, please: we like to keep this app simple.

**Comment by 4313testing** [comment]
i suggest this javascript function 
  <script>
    function validateBirthDate() {
      var birthDateInput = document.getElementById("birthDate");
      var birthDateValue = birthDateInput.value;
      var currentDate = new Date();

      var birthDate = new Date(birthDateValue);
      var currentYear = currentDate.getFullYear();
      var currentMonth = currentDate.getMonth() + 1;
      var currentDay = currentDate.getDate();

      var birthYear = birthDate.getFullYear();
      var birthMonth = birthDate.getMonth() + 1;
      var birthDay = birthDate.getDate();

      if (birthYear > currentYear ||
        (birthYear === currentYear && birthMonth > currentMonth) ||
        (birthYear === currentYear && birthMonth === currentMonth && birthDay > currentDay)) {
        alert("Invalid birth date. Please select a valid date.");
        birthDateInput.value = "";
        return false;
      }

      return true;
    }
  </script>

And also add the onsubmit in the form clause
<form th:object="${pet}" class="form-horizontal" method="post" onsubmit="return validateBirthDate()">
and this 
 <input
        th:replace="~{fragments/inputField :: input ('Birth Date', 'birthDate', 'date')}" id="birthDate" />
        
        
I can directly add a Pull request if you want

**Comment by dsyer** [comment]
We don't have any JavaScript in the app as it stands and I'd quite like to keep it that way. We do already have server side validation and error handling (just not much of it). It would be better to tackle it there if you are going to send a pull request.

**Comment by 4313testing** [comment]
@dsyer this is a simple solution directly in the controller i think this the best solution 
`LocalDate currentDate = LocalDate.now();
		if (pet.getBirthDate() != null && pet.getBirthDate().isAfter(currentDate)) {
			result.rejectValue("birthDate", "invalid", "Invalid birth date. Please select a valid date.");
		}`

**Comment by dsyer** [comment]
Are you sending a PR?

**Comment by 4313testing** [comment]
i am sending in few min .

**Comment by 4313testing** [comment]
Pull Request is Done #1284

**Comment by dsyer** [comment]
Merged
