### ISSUE TITLE
Duplicate Pet Name on Edit Pet 

### ISSUE THREAD

**Issue by 4313testing** [spring-projects/spring-petclinic#1287]
when editing a pet you can put the name of an already existing pet name for the same owner 
![image](https://github.com/spring-projects/spring-petclinic/assets/135747487/8ac45d13-987c-4837-ba63-23b39d2c0ffa)

**Comment by 4313testing** [comment]
@dsyer i can provide the solution in PR if you want

**Comment by dsyer** [comment]
I don’t think it’s worth the extra code, I’m afraid, but I don’t mind if you want to show us how to do it.

**Comment by 4313testing** [comment]
no problem i am sure you know how to fix it.

**Comment by 4313testing** [comment]
@dsyer  i added the solution in this PR #1288
please check it and see if its helpfull

**Comment by dsyer** [comment]
I merged it but then the build failed so I reverted. Can you have a look and send another PR please?

**Comment by 4313testing** [comment]
yes it was because of spring-javaformat check 
now its fixed you can use this new PR #1290
