### ISSUE TITLE
JdbcSQLDataException occurs when passing long  name  

### ISSUE THREAD

**Issue by 4313testing** [spring-projects/spring-petclinic#1291]
when you input a long name in owner form or pet form JdbcSQLDataException shows in the console .
So i think we should avoid this Exception from happening during runtime .
![image](https://github.com/spring-projects/spring-petclinic/assets/135747487/ce1d8922-431e-4c1f-8beb-a50a04369dcd)

Reason:
![image](https://github.com/spring-projects/spring-petclinic/assets/135747487/95b1dd22-e1b8-44b2-ba94-612815ffdd86)

**Comment by dsyer** [comment]
I really don't care that much. You get the error page right? Isn't that good enough for a demo app?

**Comment by 4313testing** [comment]
yes i understand but i think that its not good to let Runtime Exception related to SQL to happens when running application 
if you dont care no problem but if you want to eliminate this exception i can send you a PR.
