### ISSUE TITLE
[Suggestion] Adding messages in Korean

### ISSUE THREAD

**Issue by Anthony-Park** [spring-projects/spring-petclinic#1299]
Hello.
I know this sample project doesn't need all languages as mentioned before [[Adding new message in Spanish]](
https://github.com/spring-projects/spring-petclinic/pull/631#issuecomment-648334174).

I agree and respect it, but I request consideration as next.
It's good to show Spring, and only this has internationalization in Spring sample projects.
It's interesting for users of PetClinic who use foreign languages, such as Korean.
Other languages can't leave an impression because they are unreadable.

Please, feel free to assign this to me.
Thank you.

**Comment by dsyer** [comment]
You can send a pull request. I think we should have at least one non-European language, and the Chinese one seems to have stalled.

**Comment by Anthony-Park** [comment]
Thanks for your review, my suggestion, and your approval.
I will submit a PR.
Thank you.

**Comment by Anthony-Park** [comment]
@dsyer, I've included a Korean message file in this PR #1328. 
Would you kindly review it when you have a moment? 
I appreciate your assistance. 
Thank you.
