### ISSUE TITLE
N+1 Queries in Owners endpoint

### ISSUE THREAD

**Issue by tekshteint** [spring-projects/spring-petclinic#1302]
While digging around the Spring Petclinic I found this issue running [digma.ai](http://digma.ai/) on the project. The n+1 situation arises in two situations:

1) Making a parameterless GET request on /owners
2) Using the webpage and searching for an empty string

We can see that in the traces, side panel, and even the query behind the issue. This issue can be replicated using a simple shell script to concurrently load the /owners endpoint or even just running an empty string search a few times from the webpage.
![BeforeTrace](https://github.com/spring-projects/spring-petclinic/assets/36021918/0d421021-9615-42e5-9d4c-f0bef42764ec)
![SidePaneView](https://github.com/spring-projects/spring-petclinic/assets/36021918/59443937-ede2-45bf-a7bb-12f74cfde40a)
![AfflictingQuery](https://github.com/spring-projects/spring-petclinic/assets/36021918/2b7173dd-8efa-45cd-92fe-f7a9d3f7040d)

My proposed fix resolves the n+1 issue and reduces the amount of un-necessary queries. We can see that in the new traces and the updated side panel view when testing in the same manner. Here's the new query I used to resolve this issue.
![AfterTrace](https://github.com/spring-projects/spring-petclinic/assets/36021918/f6eb6e1a-0d0d-4268-a4a7-286ca302bbef)
![AfterOverview](https://github.com/spring-projects/spring-petclinic/assets/36021918/d28a62d3-435c-4b73-8547-d22e488704a7)
![AfterQuery](https://github.com/spring-projects/spring-petclinic/assets/36021918/7211a9fe-1c8e-427a-aaed-6bbf5550f871)

**Comment by dsyer** [comment]
Bear in mind though that n=5, so I don't think it's necessarily a huge problem. Thanks for the pull request though.
