### ISSUE TITLE
Add owner

### ISSUE THREAD

**Issue by MohammedFairoz1** [spring-projects/spring-petclinic#1320]
Add owner needs to be in the nav bar
![Screenshot (12)](https://github.com/spring-projects/spring-petclinic/assets/114471735/bd8e123a-5812-4648-9a48-188ff33692c8)
when I click on find the owner at that time I can also able to see add owner but it needs to be separated

**Comment by Bobzero23** [comment]
what do you mean by separated? can you clarify a little bit

**Comment by Aman80900** [comment]
I have created a pull request for this issue
https://github.com/spring-projects/spring-petclinic/pull/1323

**Comment by MohammedFairoz1** [comment]
@Bobzero23 add owner need to be in navbar

**Comment by Bobzero23** [comment]
> 

can I fix that? or have you already done that

**Comment by MohammedFairoz1** [comment]
yes, you can...

**Comment by Bobzero23** [comment]
> yes, you can...

@MohammedFairoz1  have created two pull request to fix this issue.

**Comment by codespearhead** [comment]
@Bobzero23 PR, which I assume were #1346 and #1347, were closed because [they didn't sign the CLA in time](https://github.com/spring-projects/spring-petclinic?tab=readme-ov-file#contributing).

@Aman80900 Your PR #1323 was closed. I added more information there.
