### ISSUE TITLE
The "Find owner" functionality should be based on the first name, last name, and city, which is only based on last name

### ISSUE THREAD

**Issue by Jitendrajadhav1990** [spring-projects/spring-petclinic#1349]
To improve the "Find Owner" functionality, it would be more user-friendly to allow searching by various inputs. However, in this application, using first name, last name, and city is more convenient than relying solely on remembering the last name.
![Screenshot (1367)](https://github.com/spring-projects/spring-petclinic/assets/144873384/c37738b2-af23-4c49-b699-8d452ded2dab)

**Comment by dsyer** [comment]
I don't think I care. It would add a bunch of code and one of the main features of the app is to be simple. Thanks, though.
