### ISSUE TITLE
Owners should not be allowed to enter duplicate mobile numbers.

### ISSUE THREAD

**Issue by Jitendrajadhav1990** [spring-projects/spring-petclinic#1350]
Owners should not be allowed to enter duplicate mobile numbers, this will create confusion and trouble  
![Screenshot (1369)](https://github.com/spring-projects/spring-petclinic/assets/144873384/52ceb589-5ff5-4893-a848-4a370432a6b2)

**Comment by dsyer** [comment]
I honestly don't think it's worth the extra code to defend against this. If you want to make a suggestion you could send a PR, I guess, but if it's a lot of code I don't expect it will go onto main.

**Comment by nawazquazi1** [comment]
can i solve

**Comment by dsyer** [comment]
I don’t think we need this kind of complexity here. It’s a difficult decision but closing.
