### ISSUE TITLE
Telephone number validation is not user friendly while adding owner

### ISSUE THREAD

**Issue by Jitendrajadhav1990** [spring-projects/spring-petclinic#1351]
while adding owner, getting validation for Telephone is "  numeric value out of bounds (<10 digits>.<0 digits> expected)
must not be blank" which will can be user friendly like "Please enter a valid 10 digit mobile number
![Screenshot (1370)](https://github.com/spring-projects/spring-petclinic/assets/144873384/d3ad2f7f-d2b7-4d07-a0c6-318900070b99)

**Comment by dsyer** [comment]
That one should be trivial to fix. It's just a message isn't it? You could start with a PR for the default (English).

**Comment by Aayush-Kapur** [comment]
Hey @dsyer , I've Added User Friendly Messages for blank fields. Please review this PR #1361 .
I've also attached screenshots of before and after for better understanding of output of my commit.

**Comment by codespearhead** [comment]
@Jitendrajadhav1990 It seems that #1361 (merged by accident, now reverted) fixes the same issue as #1483, which was merged three week ago. Should this issue be closed?
