### ISSUE TITLE
Background from datapicker is 'transparent'

### ISSUE THREAD

**Issue by lukasz-szewc** [spring-projects/spring-petclinic#137]
Screenshot of issue here:

http://postimg.org/image/hzpfbl2pf/

**Comment by liouxiao** [comment]
The same issue in my place (happened in both Safari & Firefox running on Mac OS).

I add a CCS style in `petclinic.css` file to fix it:

```

.ui-datepicker {
	background-color: #d0e0c0;
}
```

**Comment by arey** [comment]
I believe this issue is fixed ton the bootstrap3 branch. Could you please confirmed?

**Comment by liouxiao** [comment]
Just confirm it, bootstrap3 branch has no this issue now. Thanks.

**Comment by arey** [comment]
Thanks @liouxiao. So I close this issue.
