### ISSUE TITLE
Css issue with 'width' 

### ISSUE THREAD

**Issue by lukasz-szewc** [spring-projects/spring-petclinic#138]
Either header must be short and tables must fit in, or header should be extended.

Picture showing problem here:

http://postimg.org/image/azn640x5f/

**Comment by arey** [comment]
@lukasz-szewc , I don't understand what is the issue? Do you propose to remove the width?

**Comment by lukasz-szewc** [comment]
Please look at the header with menu. It is short and (presumably) should determine the borders of the page. Every content below should 'fit' within. This table violates that boundary, and whole page does not look symmetric at all. 

Here is another screen from app which in my opinion is correct:
I think that this is how this should look like:

http://postimg.org/image/mjw6e61h9/c7a66ef9/

Container class in css is quite clear about it: width: 700px;

**Comment by lasiqueira** [comment]
Hello, I ran into the same issue. The CSS breaks when you enter the vetList.jsp or the ownerList.jsp.

I checked the code and chrome console and pinpointed what is the problem. 

I could fix that if you guys let me. I never contributed to an open source project before so I don't quite understand yet how to do it though.

**Comment by arey** [comment]
Don't hesitate to submit a fix through a pull request.
For your information, I'm woking on Bootstrap 3 migration. Thus css will be updated. Maybe you may waithis update (planed for next week) then check if this issue is still there?

**Comment by lasiqueira** [comment]
Oh, ok, I will wait then.

Thanks!

**Comment by liouxiao** [comment]
actually this issue comes from `dandelion-datatables`, which inserts another `bootstrap.css` after `petclinic.css` in html head section, and the style file specifies `.container` width as `1170px` (in line 5833).

to quick fix it, we'd just specify the width at the html element in related jsp file, e.g. `ownerList.jsp`:

```
<body>
<div class="container" style="width: 700px">
...
```

**Comment by lasiqueira** [comment]
Actually the best fix in my opinion is to remove the theme, since we already have bootstap in the application.

I created a pull request for that.

**Comment by liouxiao** [comment]
@lasiqueira your fix looks more reasonable, thanks!

**Comment by arey** [comment]
Could you tell me please if there is a similar issue on the bootstrap3 branch?
https://github.com/spring-projects/spring-petclinic/tree/bootstrap3

**Comment by liouxiao** [comment]
In bootstrap3 branch, it looks by design the banner has a fixed width (600px), while the rest of page content has a full width, obviously there's no such issue anymore. (but maybe somebody would like the original layout design - "all content in a fixed width", :-)
