### ISSUE TITLE
Unable to format code on gradle

### ISSUE THREAD

**Issue by ThomasPerkins1123** [spring-projects/spring-petclinic#1436]
When using petclinic with maven you can format the code with `mvn spring-javaformat:apply`. However no such option exists when using gradle as it is missing the `io.spring.javaformat` plugin. When writing/modifying code you should be able to run the same auto formatting on gradle.

Fixed by #1433

**Comment by dsyer** [comment]
I merged that PR, but it breaks the build pretty badly. See conversation in #1437.
