### ISSUE TITLE
The owner list described in the readme.md file was not found.

### ISSUE THREAD

**Issue by flyisland** [spring-projects/spring-petclinic#1440]
The owner list described in the readme.md file is as below:
![](https://cloud.githubusercontent.com/assets/838318/19727082/2aee6d6c-9b8e-11e6-81fe-e889a5ddfded.png)

But I got this after clicking the "Find Owners" tab
<img width="884" alt="image" src="https://github.com/spring-projects/spring-petclinic/assets/547085/f4b626ee-a6d2-40a6-abdb-21a223027fb4">

**Comment by lukasdo** [comment]
@flyisland the table with all owners is only displayed when you search for owners and there are multiple results. If you hit the "Find Owner" Button without a search term you can see the table.

**Comment by flyisland** [comment]
@lukasdo thanks
