### ISSUE TITLE
do we have swagger in petclinic

### ISSUE THREAD

**Issue by ozkanpakdil** [spring-projects/spring-petclinic#1462]
when I look at the code I do not see any and I just wanted to make sure that I am not missing anything. Do we have swagger in petclinic ?

or any other type of openapi documentation tool to describe the service?
Thanks

**Comment by dsyer** [comment]
There's not much of an API really to speak of, so there isn't really much demand. There is one `@ResponseBody` mapping (for `/vets`), but the application itself doesn't use it.
