### ISSUE TITLE
Shouldn't the "name" property of the NamedEntity Bean be non nullable?

### ISSUE THREAD

**Issue by zyberzebra** [spring-projects/spring-petclinic#1472]
```java
	@Column(name = "name", nullable = false)
	private String name;
```

**Comment by dsyer** [comment]
I'm not super excites about changing this. It's more likely to lead to other bugs showing up unexpectedly, and doesn't really change the behaviour of the app as far as I can see.

**Comment by snicoll** [comment]
Ditto.
