### ISSUE TITLE
Why not use Lombok?

### ISSUE THREAD

**Issue by RaveenDharmasiri** [spring-projects/spring-petclinic#1484]
Why don't we try Lombok and reduce the boilerplate code like getters, setters, constructor creation etc..?

```
<dependency>
  <groupId>org.projectlombok</groupId>
  <artifactId>lombok</artifactId>
  <optional>true</optional>
</dependency>
```

**Comment by erfannvb** [comment]
Hello friend. I think it's a good suggestion to use Lombok dependency.
It can help the project to be more readable too.
If there is not any problem I'd be glad to work on this issue.
@RaveenDharmasiri

**Comment by snicoll** [comment]
We're not going to start a debate around lombok here. We have no intention of using it.
