### ISSUE TITLE
Why do you have to add pet to owner after you find pet by id?

### ISSUE THREAD

**Issue by aagarw33** [spring-projects/spring-petclinic#149]
I am not sure if you have to addPet() to owner again, after you find the pet for that owner using owner's ID.
   
#####     owner.addPet(pet);
```java
@Override
    public Pet findById(int id) throws DataAccessException {
        JdbcPet pet;
        try {
            Map<String, Object> params = new HashMap<>();
            params.put("id", id);
            pet = this.namedParameterJdbcTemplate.queryForObject(
                "SELECT id, name, birth_date, type_id, owner_id FROM pets WHERE id=:id",
                params,
                new JdbcPetRowMapper());
        } catch (EmptyResultDataAccessException ex) {
            throw new ObjectRetrievalFailureException(Pet.class, id);
        }
        Owner owner = this.ownerRepository.findById(pet.getOwnerId());
        owner.addPet(pet);
        pet.setType(EntityUtils.getById(findPetTypes(), PetType.class, pet.getTypeId()));
        List<Visit> visits = this.visitRepository.findByPetId(pet.getId());
        for (Visit visit : visits) {
            pet.addVisit(visit);
        }
        return pet;
    }
```

**Comment by liouxiao** [comment]
I think it is a bug, it should (1) make the `setOwner` method in Pet.java to be `public`, and (2) replace `owner.addPet(pet);` with `pet.setOwner(owner);`

**Comment by aagarw33** [comment]
When you are finding the pet by owner's id, it already means that pet is assigned to that owner. Help me understand here why do we have to do `pet.setOwner(owner)` or `owner.addPet(pet)`?

**Comment by liouxiao** [comment]
I guess, it is all because of "accomplishment", the Pet class has a variable called `owner`, if not set back `owner` object, it will return a `pet` with null owner (you'd debug it to see the value), obviously this kind of incomplete `pet` object is not acceptable for some use cases.

**Comment by aagarw33** [comment]
Yes I did notice that. It is confusing for me though.

**Comment by arey** [comment]
I will review it next week.

**Comment by arey** [comment]
The ```ownerRepository.findById``` method already retrieves the owner and all its pets. Thus we could refactor the JDBC implementation by retrieving the owner id of the given pet id, then call ```ownerRepository.findById```  and then iter trough the owner's pet set in order to find the pet before returning it. Does the code will become less confusing ?

**Comment by aagarw33** [comment]
I think the query is doing it all `
                "SELECT id, name, birth_date, type_id, owner_id FROM pets WHERE id=:id"`

**Comment by arey** [comment]
Address, telephone and city of the owner are not loaded.

**Comment by aagarw33** [comment]
Oh yes! may be the work around you are saying is better.

**Comment by arey** [comment]
Based on my proposition, I've commited some simplifications. Is it ok for you?

**Comment by aagarw33** [comment]
Yes this is cool. Thanks!

**Comment by arey** [comment]
Great. Thus I close this issue. Thanks for the report and your patience.
