### ISSUE TITLE
Several methods invalidly declares throws some derived RuntimeException

### ISSUE THREAD

**Issue by michael-o** [spring-projects/spring-petclinic#15]
As per contract of the RuntimeException, it is never written into the throws clause but in JavaDoc only. E.g., EntityUtils#getById throws ObjectRetrievalFailureException which is a RuntimeException and has therefore to be removed.

```java
public static <T extends BaseEntity> T getById(Collection<T> entities, Class<T> entityClass, int entityId) {
        for (T entity : entities) {
            if (entity.getId().intValue() == entityId && entityClass.isInstance(entity)) {
                return entity;
            }
        }
        throw new ObjectRetrievalFailureException(entityClass, entityId);
    }
```
Same applies for all Repository classes. There is a good reason why Spring uses unchecked exceptions. It lets the developer decide wether he wants to deal with it or not.

**Comment by michael-o** [comment]
Has this been fixed in the code or why was this closed without reason?

**Comment by michaelisvy** [comment]
Hi Michael,
sorry for that. We don't think that many people use the Javadoc in the case of Petclinic. People just look at the code.
So we're only declaring some RuntimeExceptions in the signature when they're especially important.

No strong opinion on that. We just want to make life easier for people who are getting started with Spring.

Cheers,
Michael.
