### ISSUE TITLE
I see some i18n pieces in the code. Is toggling between languages built in somewhere or does that need to be added?

### ISSUE THREAD

**Issue by daniel9x** [spring-projects/spring-petclinic#151]

**Comment by liouxiao** [comment]
Basically it's not needed - I had a similar pull request but be rejected, see https://github.com/spring-projects/spring-petclinic/pull/80

The explanation is: `Our point is just to have a "fairly" simple sample application for beginners to learn and I don't think we should add I18N to the master branch.`

BTW, I have a forked project which includes full i18n support as well as Chinese translation, you'd find it at https://github.com/liouxiao/spring-petclinic

**Comment by arey** [comment]
@liouxiao and @michaelisvy give you the answer. We don't plan to add switching language feature.
