### ISSUE TITLE
Gradle version could be upgraded

### ISSUE THREAD

**Issue by andrzejsydor** [spring-projects/spring-petclinic#1539]

**Comment by dsyer** [comment]
It would be trivial to upgrade to 8.7 if anyone feels like sending a pull request.

**Comment by patbaumgartner** [comment]
This was done already with the commit by @snicoll - See: https://github.com/spring-projects/spring-petclinic/commit/85ae6fbc802ba6a57122dd47e4acf4e8a213b912

I think this issue #1539 can be closed.
