### ISSUE TITLE
Why redirectAttributes.addFlashAttribute next return VIEWS_OWNER_CREATE_OR_UPDATE_FORM;?

### ISSUE THREAD

**Issue by omelet3032** [spring-projects/spring-petclinic#1544]
```
@PostMapping("/owners/{ownerId}/edit")
	public String processUpdateOwnerForm(@Valid Owner owner, BindingResult result, @PathVariable("ownerId") int ownerId,
										 RedirectAttributes redirectAttributes) {
		if (result.hasErrors()) {
			redirectAttributes.addFlashAttribute("error", "There was an error in updating the owner.");
			return VIEWS_OWNER_CREATE_OR_UPDATE_FORM;
		}

		owner.setId(ownerId);
		this.owners.save(owner);
		redirectAttributes.addFlashAttribute("message", "Owner Values Updated");
		return "redirect:/owners/{ownerId}";
	}
```

Im looking this code.
if client want to see  "There was an error in updating the owner.", 
i think that  return "redirect:/owners/{ownerId}";' is right, not VIEWS_OWNER_CREATE_OR_UPDATE_FORM;

I dont understand why use 'redirectAttributes.addFlashAttribute'

Maybe Spring developer probably has a specific intent.
Could you check this code?

**Comment by dsyer** [comment]
You are right that it is a mistake I think, but wrong about the return value - it is better to render the owner details directly if there is an error. The `RedirectAttributes` are discarded if the response is not a redirect, so the mistake is harmless. If anyone wants to fix it please reference this issue in the PR.

**Comment by dsyer** [comment]
The PR was closed without merging so the issue still exists but it's not hugely pressing. Another PR would probably be fine.
