### ISSUE TITLE
why JdbcTemplate was annotated on the "@Bean(name="transactionManager")"?

### ISSUE THREAD

**Issue by phxism** [spring-projects/spring-petclinic#156]
spring-petclinic-javaconfig\src\main\java\org\springframework\samples\petclinic\config\JdbcConfig.java
`@Bean(name="transactionManager")
    public JdbcTemplate jdbcTemplate() {
    	return new JdbcTemplate(dataSource);
    }`
this jdbcTemplate can be named with "transactionManager"?

**Comment by aagarw33** [comment]
jdbcTemplate needs a transactionManager to perform ops. `@Bean(name="transactionManager")` should` be reference to the transactionManager.

**Comment by phxism** [comment]
But the meaning of the attribute "name "of "Bean" is the name of the bean.if it's like what you say ,what about the Namedparametersjdbctemplate.                                [  
    @Bean(name="transactionManager")
    public JdbcTemplate jdbcTemplate() {
    	return new JdbcTemplate(dataSource);
    }
    
    @Bean
    public NamedParameterJdbcTemplate namedParameterJdbcTemplate() {
    	return new NamedParameterJdbcTemplate(dataSource);
    }]()

**Comment by arey** [comment]
Thanks for this comment
