### ISSUE TITLE
Petclinic on Cloud Foundry

### ISSUE THREAD

**Issue by arey** [spring-projects/spring-petclinic#160]
For demonstration purpose, we would like to host Spring Petclinic on Cloud Foundry.
It used to be hosted on Pivotal Web Services and it was kind of ok: http://spring-petclinic.cloudfoundry.com/ Only issue Michael noticed is that it used to have issues every 2 to 3 weeks. It would either restart or crash completely (so we had to redeploy it). It might be related to the application itself.
That was one year ago, so it might also be related to some issues with PWS that have been fixed in the meantime. 
See #126

**Comment by verydapeng** [comment]
So far I have been running my own petclinic deployment (springboot branch) for about 1 month, it did crashed once (for some unknown reason) but cloud foundry successfully revived it 

It seems to be safe enough to deploy pet clinic on PWS again

**Comment by arey** [comment]
@verydapeng are you authorized to use the same URL: http://spring-petclinic.cloudfoundry.com/ ?

**Comment by verydapeng** [comment]
@arey I don't think cloudfoundry.com domain is still used to host anything

Right now "petclinic.cfapps.io" and "spring-petclinic.cfapps.io" are also been used

@michaelisvy Any suggestion?

**Comment by dsyer** [comment]
Maybe this is redundant now that you can run it yourself with one click (8394b7d)?
