### ISSUE TITLE
[ERROR] Some problems were encountered while processing the POMs:

### ISSUE THREAD

**Issue by dyego1912** [spring-projects/spring-petclinic#1627]
[FATAL] Non-resolvable parent POM for org.springframework.samples:spring-petclinic:3.3.0-SNAPSHOT: The following artifacts could not be resolved: org.springframework.boot:spring-boot-starter-parent:pom:3.3.0 (absent): Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:3.3.0 from/to spring-snapshots (https://repo.spring.io/snapshot): PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target and 'parent.relativePath' points at wrong local POM @ line 10, column 9

**Comment by sn0111** [comment]
@dyego1912  I didn't encounter any problems with the pom.xml file. Please check your ~/.m2/settings.xml and proxy configurations.

**Comment by dsyer** [comment]
I think it must be a local (network?) issue.
