### ISSUE TITLE
Ice Breaker Contribution - Replacing != with !Objects.equals()

### ISSUE THREAD

**Issue by mosbat** [spring-projects/spring-petclinic#1663]
Hi guys, this is my first open-source contribution so forgive me if the issue I'm pushing is so silly and irrelevant. However, I'd appreciate any feedback or ideas; I'd like to get to the habit of contributing to open-source outside corporate environment.

I'm going to begin contributing quite often.

This will be an opportunity for me to get familiar with how things work here and to improve myself.

Thank you!

My pull request is below here!

https://github.com/spring-projects/spring-petclinic/pull/1662

**Comment by dsyer** [comment]
PR closed
