### ISSUE TITLE
Small Code Cleanup

### ISSUE THREAD

**Issue by mosbat** [spring-projects/spring-petclinic#1664]
I inspected code and found the following:
1- Unused imports.
2- Made some variables final since they are part of DTOs.

**Comment by dsyer** [comment]
No CLA in PR

**Comment by mosbat** [comment]
> No CLA in PR

Thank you for the feedback. I think that I signed the CLA for the PR but please don't mind me if I missed something. I'm learning.  Btw, I see the CLA signed in the PR's checks...

**Comment by dsyer** [comment]
Sorry, I think I was looking at the wrong PR. It’s merged now.
