### ISSUE TITLE
None Access to H2-Console

### ISSUE THREAD

**Issue by may040** [spring-projects/spring-petclinic#1701]
When entering the URL for the H2 console, the website does not load, so access to the database is not possible.

Environment:

- Database H2
- Maven Project
- IntelliJ IDEA

**Comment by may040** [comment]
I have adjusted the additional.properties accordingly. Fix #1700. Thanks!

**Comment by dsyer** [comment]
The console is available by default if you run from the test classes. Probably we should just change the README to make that clear, rather than making it available "in production".
