### ISSUE TITLE
Aplicación de Principios SOLID

### ISSUE THREAD

**Issue by marciatorresg** [spring-projects/spring-petclinic#1716]
Hemos identificado varias violaciones a los principios SOLID en el proyecto Spring Petclinic. A continuación, se detallan las violaciones encontradas en cada clase y las soluciones propuestas para corregirlas, junto con el código fuente actualizado y los diagramas UML.

Clase ClinicServiceImpl
Violaciones:

SRP: Maneja la lógica de negocio para dueños, mascotas y veterinarios en una sola clase.
OCP: No está diseñada para permitir la extensión sin modificar el código existente.
LSP: La implementación de métodos específicos puede no cumplir con las expectativas de las interfaces que podrían extender esta clase.
Solución Propuesta:

División de responsabilidades en servicios específicos (OwnerService, PetService, etc.).
Diseño para permitir la extensión sin modificar la clase base.
Cumplimiento de contratos de interfaces.
java
Copiar código
// OwnerService.java
public interface OwnerService {
    Owner findOwnerById(int id);
    void saveOwner(Owner owner);
    List<Owner> findAllOwners();
}

// OwnerServiceImpl.java
public class OwnerServiceImpl implements OwnerService {
    private final OwnerRepository ownerRepository;

    public OwnerServiceImpl(OwnerRepository ownerRepository) {
        this.ownerRepository = ownerRepository;
    }

    @Override
    public Owner findOwnerById(int id) {
        return ownerRepository.findById(id).orElse(null);
    }

    @Override
    public void saveOwner(Owner owner) {
        ownerRepository.save(owner);
    }

    @Override
    public List<Owner> findAllOwners() {
        return ownerRepository.findAll();
    }
}

// PetService.java
public interface PetService {
    Pet findPetById(int id);
    void savePet(Pet pet);
    List<Pet> findAllPets();
}

// PetServiceImpl.java
public class PetServiceImpl implements PetService {
    private final PetRepository petRepository;

    public PetServiceImpl(PetRepository petRepository) {
        this.petRepository = petRepository;
    }

    @Override
    public Pet findPetById(int id) {
        return petRepository.findById(id).orElse(null);
    }

    @Override
    public void savePet(Pet pet) {
        petRepository.save(pet);
    }

    @Override
    public List<Pet> findAllPets() {
        return petRepository.findAll();
    }
}
Clase Pet
Violaciones:

SRP: Contiene lógica de validación además de los datos de la mascota.
OCP: No está diseñada para permitir la extensión para nuevos tipos de mascotas sin modificar la clase.
LSP: Si se extiende incorrectamente, podría romper el comportamiento esperado.
Solución Propuesta:

Separar la lógica de validación en una clase diferente.
Usar herencia para permitir la extensión sin modificar la clase base.
Asegurar que las subclases cumplen con el comportamiento esperado de la clase base.
java
Copiar código
// Pet.java
public abstract class Pet {
    private int id;
    private String name;

    // Getters and Setters
    public abstract String getType();
}

// Dog.java
public class Dog extends Pet {
    @Override
    public String getType() {
        return "Dog";
    }
}

// Cat.java
public class Cat extends Pet {
    @Override
    public String getType() {
        return "Cat";
    }
}

// PetValidator.java
public class PetValidator {
    public static boolean isValid(Pet pet) {
        // Lógica de validación aquí
        return true;
    }
}
Clase Visit
Violaciones:

SRP: Podría tener lógica de negocio mezclada con los datos de la visita.
OCP: No está diseñada para permitir la extensión sin modificar la clase.
LSP: Podría no cumplir con las expectativas de BaseEntity.
Solución Propuesta:

Mover la lógica de negocio a servicios específicos.
Asegurar que la clase Visit puede ser extendida sin modificar el código existente.
Asegurar que Visit cumple con el contrato de BaseEntity.
java
Copiar código
// Visit.java
public class Visit extends BaseEntity {
    private LocalDate date;
    private String description;

    // Getters and Setters
}

// VisitService.java
public interface VisitService {
    void saveVisit(Visit visit);
    Visit findVisitById(int id);
    List<Visit> findAllVisits();
}

// VisitServiceImpl.java
public class VisitServiceImpl implements VisitService {
    private final VisitRepository visitRepository;

    public VisitServiceImpl(VisitRepository visitRepository) {
        this.visitRepository = visitRepository;
    }

    @Override
    public void saveVisit(Visit visit) {
        visitRepository.save(visit);
    }

    @Override
    public Visit findVisitById(int id) {
        return visitRepository.findById(id).orElse(null);
    }

    @Override
    public List<Visit> findAllVisits() {
        return visitRepository.findAll();
    }
}

**Diagramas UML:**
![{214A38CC-B950-43F2-957A-BFF88EC73452}](https://github.com/user-attachments/assets/bbec3005-7d74-4497-8e34-af63fcd78683)

![{656FBBED-430F-4068-8D40-F4065A08792F}](https://github.com/user-attachments/assets/9436fde1-fc0e-49f4-a58e-1908b44994a2)

**Comment by wickdynex** [comment]
Thank you @marciatorresg  for pointing out this design pattern issue🥰, but this is just a tiny project🤔 before 10 years, and I also have no idea whether to refactor it as you mentioned. Definitely, it's a good issue👍. Btw, could u please adjust the display format of your comment? It's a little messy🥺.
