### ISSUE TITLE
Replace Explicit Getters and Setters with @Data Annotation in BaseEntity Class

### ISSUE THREAD

**Issue by abdurraffaysyed** [spring-projects/spring-petclinic#1720]
Hi everyone,

I am new to this project, and while exploring the codebase, I noticed an area where we can potentially improve the readability and maintainability of the code.

### Current Implementation
The "BaseEntity" class includes explicitly implemented getters and setters for the id attribute. 

### Change To Be Done
As there are no complex computations or logic associated with these methods, we could use the **Data** annotation from the **Lombok** library to simplify this.

### Benefits

Code Simplification: By using **Data**, we eliminate the need for boilerplate code for getters, setters.
Maintainability: Reduces the likelihood of introducing errors when manually maintaining boilerplate code.

If this sounds like a valid enhancement, I’d be happy to create a PR for this change. I’d love to hear feedback or thoughts on this!

Best regards,
Syed Muhammad Abdurraffay

**Comment by dsyer** [comment]
No thanks.
