### ISSUE TITLE
Gitpod support is broken after latest changes for codespaces.

### ISSUE THREAD

**Issue by ESJBRE1** [spring-projects/spring-petclinic#1721]
It is neccesary to restore previous Dockerfile to add support for Gitpod.

- https://github.com/spring-projects/spring-petclinic/blob/main/.gitpod.yml
- https://github.com/spring-projects/spring-petclinic/commit/12eb8b1ff3b463fa3cf430fd202449f41397291d#diff-13bd9d7a30bf46656bc81f1ad5b908a627f9247be3f7d76df862b0578b534fc6

**Comment by dsyer** [comment]
See 42e2c74
