### ISSUE TITLE
Refactor Owner Directory Structure for Component Separation

### ISSUE THREAD

**Issue by abdurraffaysyed** [spring-projects/spring-petclinic#1729]
### Current Implementation
The project structure places all classes related to pets, owners, and visits in a single directory. This organization can make the codebase harder to navigate and maintain as the project grows. To improve clarity and scalability, I propose refactoring the directory structure by segregating these classes into separate directories based on their functionality.

### Proposed Solution:
Create distinct directories for each component:

pets: For all pet-related classes and functionality.
owners: For all owner-related classes and functionality.
visits: For all visit-related classes and functionality.
Move the relevant classes and files into their respective directories.
Example:

Move Pet.java, PetController.java, etc., to the pets directory.
Move Owner.java, OwnerController.java, etc., to the owners directory.
Move Visit.java, VisitController.java, etc., to the visits directory.
Update imports throughout the project to reflect the new structure.

### Benefits:
Improved Readability: Each directory will contain only the files relevant to its component, making it easier for developers to find and understand code.
Better Scalability: As new features or functionality are added, the modular structure will help maintain organization.
Easier Maintenance: Fixes or updates related to a specific component can be implemented and tested more efficiently.

I recommend performing this refactoring as a separate commit to make the changes easier to track.
Let me know if there's any feedback or additional considerations before I start working on this!

**Comment by dsyer** [comment]
The design is already intentionally modular. Pets and visits are part of the owner entity (in DDD terms). Any further separation is a kind of overengineering. Thanks for the suggestion, though.

**Comment by abdurraffaysyed** [comment]
Thank you for your response and for clarifying the design considerations. I understand that the current modular structure, with pets and visits as part of the owner entity in Domain-Driven Design (DDD) terms, is intentional. I appreciate your insight and will take this into account moving forward. Consequently, I will close the associated pull request for this issue to align with the project's design principles.
