### ISSUE TITLE
Error occorred when generate-sources

### ISSUE THREAD

**Issue by icedme666** [spring-projects/spring-petclinic#1744]
1. I follow the example on official website, then got the error: could not find not symbol: class SmallTest.
2. and the file on target/generated-sources/graphwalker is cache.json, not SmallTest.java.I throught the error occorred when generate-sources. 
3. I use the `mvn clean` and retry, but it doesn't work.
4. my env is: 
java -version
java version "23.0.1" 2024-10-15
Java(TM) SE Runtime Environment (build 23.0.1+11-39)
Java HotSpot(TM) 64-Bit Server VM (build 23.0.1+11-39, mixed mode, sharing)

mvn --version 
Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)
Maven home: /Users/iced_me/Developer/Java/apache-maven-3.9.9
Java version: 23.0.1, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-23.jdk/Contents/Home
Default locale: zh_CN_#Hans, platform encoding: UTF-8
OS name: "mac os x", version: "13.2.1", arch: "x86_64", family: "mac"

--------------------------------------------------------------------------
cache.json is:
{"/Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/resources/com/company/SmallTest.json":{"modified":1734345031816,"generated":false}}

--------------------------------------------------------------------------
terminal error is:
myProject mvn compile exec:java -Dexec.mainClass="com.company.Runner"

[INFO] Scanning for projects...
[INFO] 
[INFO] ------------< org.graphwalker:graphwalker-maven-archetype >-------------
[INFO] Building GraphWalker Example 4.3.3
[INFO]   from pom.xml
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- graphwalker:4.3.3:generate-sources (generate-sources) @ graphwalker-maven-archetype ---
[INFO] 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
[INFO] 
[INFO] --- resources:3.3.1:resources (default-resources) @ graphwalker-maven-archetype ---
[INFO] Copying 1 resource from src/main/resources to target/classes
[INFO] 
[INFO] --- compiler:3.6.1:compile (default-compile) @ graphwalker-maven-archetype ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[10,64] could not find not symbol: class SmallTest
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[12,3] The method will not override the method of the type
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[17,3] The method will not override the method of the type
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[22,3] The method will not override the method of the type
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[27,3] The method will not override the method of the type
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[32,3] The method will not override the method of the type
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[37,3] The method will not override the method of the type
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[42,3] The method will not override the method of the type
[INFO] 8 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.650 s
[INFO] Finished at: 2024-12-16T18:31:10+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project graphwalker-maven-archetype: Compilation failure: Compilation failure: 
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[10,64] could not find symbol
[ERROR]  symbol: class SmallTest
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[12,3] The method will not override the method of the type
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[17,3] The method will not override the method of the type
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[22,3] The method will not override the method of the type
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[27,3] The method will not override the method of the type
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[32,3] The method will not override the method of the type
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[37,3] The method will not override the method of the type
[ERROR] /Users/iced_me/Developer/Python/Auto_Test/testFramework/graphwalker/myProject/src/main/java/com/company/SomeSmallTest.java:[42,3] The method will not override the method of the type
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by dsyer** [comment]
There is no source generation here AFAIK and no `SmallTest`. Maybe you posted in the wrong project?
