### ISSUE TITLE
A Memory Leak in PetClinic

### ISSUE THREAD

**Issue by Hammam655** [spring-projects/spring-petclinic#179]
Hey,

I am running PetCinic in VM, and I am having a memory leak. Is there any thought as to why it happens and how to solve it?

Thanks,
Hammam

**Comment by arey** [comment]
Could you please help us to identify the memory leak? Wich objects remains in memory? And do you have used a profiler?

**Comment by arey** [comment]
Without any feeback, I close this issue.
