### ISSUE TITLE
Eclipse running HSQL scripts even after commenting in data-access.properties

### ISSUE THREAD

**Issue by g1patil** [spring-projects/spring-petclinic#181]
I got following error.
`WARN  XmlWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Invalid bean definition with name 'org.springframework.jdbc.datasource.init.DataSourceInitializer#0' defined in null: Could not resolve placeholder 'jdbc.initLocation' in string value "${jdbc.initLocation}"; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'jdbc.initLocation' in string value "${jdbc.initLocation}"
ERROR ContextLoader - Context initialization failed`

Actually I commented HSQL settings and uncommented MySql settings in data-access.properties file. I executed both scripts in MySql DB. In first trial, project execution was successful. I just redeployed but this time I got above error. Don't know what's going on.
One more thing, there are three more settings above HSQL settings in  same file. Should be keep them or comment ? 
Does anyone has copy of same project with just one data access method ? 
Thank you.

**Comment by arey** [comment]
In order to use the MySQL database, you have both to comment/uncomment the data-access.properties and uncomment the mysql-connector-java artefact in the pom.xml.
To switch easier between the 2 databases, an improvment could be to add a Spring and a Maven profile.

To solve your problem, do you have tried to use Maven instead of Eclipse?

**Comment by g1patil** [comment]
Yeah. I used Maven. It was successful in first run. I redeployed after a while and this time it's running the scripts . Even if I comment HSQL, it's searching for scripts and shows null exception for values that I commented .

**Comment by g1patil** [comment]
Since I executed both scripts manually from MySQL workbench, is there any way to remove the automated scripts initialization in the project ?

**Comment by vfedoriv** [comment]
In
*data-access.properties you can see:*
# Properties that control the population of schema and data for a new data
source
jdbc.initLocation=classpath:db/hsqldb/initDB.sql
jdbc.dataLocation=classpath:db/hsqldb/populateDB.sql

and in *datasource-config.xml*
this rows:


<jdbc:initialize-database data-source="dataSource">
<jdbc:script location="${jdbc.initLocation}"/>
<jdbc:script location="${jdbc.dataLocation}"/>
</jdbc:initialize-database>

So, you can
 or change rows in
*data-access.properties as*
dbc.initLocation=classpath:db/mysql/initDB.sql
jdbc.dataLocation=classpath:db/mysql/populateDB.sql


or remove rows from *datasource-config.xml*
<jdbc:script location="${jdbc.initLocation}"/>
<jdbc:script location="${jdbc.dataLocation}"/>
 (if you dont want run scripts when redeploy project).

2016-09-03 21:57 GMT+03:00 Jivan <notifications@github.com>:

**Comment by g1patil** [comment]
Thanks . That now works perfectly !!!! I appreciate your help.

**Comment by arey** [comment]
Thanks @vfedoriv I've omited the datasource-config.xml
