### ISSUE TITLE
React frontend

### ISSUE THREAD

**Issue by nilshartmann** [spring-projects/spring-petclinic#188]
Hi,

as a "Spring Boot and React enthusiast", I recently started a fork of the PetClinic that uses [React](https://facebook.github.io/react/) as Frontend for the application: https://github.com/nilshartmann/spring-petclinic/tree/reactjs. The code is based both on the Spring Boot and the AngularJS version of the sample. The frontend (React) code is implemented in [TypeScript](https://www.typescriptlang.org/).

There is still a lot of work and room for improvements, but I would like to hear if someone is interested in this version or wants to help making it better.

Looking forward to hear from you,
Nils

**Comment by arey** [comment]
Hi Nils,

Thank you for sharing your React branch. I've tried it and the application is working on my laptop.  
I don't know React so I cannot help you to improve this branch. But we can reference your repo from the README.md of the original Spring Petclinic page. Moreover, I may discuss with other Petclinic contributors on how to manage Petclinic fork that uses another front-end framework than Angular (ie. reactjs, angular 2)

Regards

Antoine

**Comment by nilshartmann** [comment]
Hi Antonie,

thanks for your answer. Would be nice to if you could add a reference in the README.md file.

If you have any news regarding front-end frameworks for Petclinic just let me know. I would be able to help and contribute in case your interested. May be it would be useful to add a REST Api to the PetClinic so that various front-ends could be built on top of it.

Regards,
Nils

**Comment by arey** [comment]
Hi Nils,

I've updated the README.md with your fork.
Your idea of adding a REST API is great. @RestController of the Spring Boot branch is a good start. We may add some Spring REST Docs. Feel free to suggest any idea in this issue or PR. Maybe do you have done some interesting changes for React?

Regards

Antoine

**Comment by vfedoriv** [comment]
Hi Antoine,

need short version REST API, just based on ClinicService interface ?
Or full CRUD version (with some extensions in basic model repository
classes - maybe we can allow add vets/specs, delete owners, pets etc.) ?

Regard,
Vitaliy

2016-10-12 20:00 GMT+03:00 Antoine Rey <notifications@github.com>:

**Comment by nilshartmann** [comment]
Hi,

note that you can find some RestControllers on the `angularjs`-Branch:

- https://github.com/spring-projects/spring-petclinic/tree/angularjs/src/main/java/org/springframework/samples/petclinic/web

and - based on that branch - in my React fork:

- https://github.com/nilshartmann/spring-petclinic/tree/reactjs/src/main/java/org/springframework/samples/petclinic/web/api

Both are based on the ClinicService interface. Building a 'full' REST Api would mean one would be more flexible in building different and more powerful frontends...

Regards
Nils

**Comment by vfedoriv** [comment]
Hi,

I didn't made detailed code analysis, but as I see, after last big commit
in angulatjs branch, we have 2 different ClinicService interface
realisation (findOwnerByLastName/findAll), some differences in controllers
path-es and differences in database/model (visits.description column size) ?

Regards,
Vitaliy

**Comment by arey** [comment]
React front-end is available here: https://github.com/spring-petclinic/spring-petclinic-reactjs
