### ISSUE TITLE
JdbcOwnerRepositoryImpl.java - namedParameterJdbcTemplate in constructor params

### ISSUE THREAD

**Issue by vfedoriv** [spring-projects/spring-petclinic#193]
Why we try inject namedParameterJdbcTemplate in constructor (and then init new) ?
____
@Repository
public class JdbcOwnerRepositoryImpl implements OwnerRepository {

    private NamedParameterJdbcTemplate namedParameterJdbcTemplate;

    private SimpleJdbcInsert insertOwner;

    @Autowired
    public JdbcOwnerRepositoryImpl(DataSource dataSource, NamedParameterJdbcTemplate namedParameterJdbcTemplate) {

        this.insertOwner = new SimpleJdbcInsert(dataSource)
            .withTableName("owners")
            .usingGeneratedKeyColumns("id");

        this.namedParameterJdbcTemplate = new NamedParameterJdbcTemplate(dataSource);

}

**Comment by arey** [comment]
You're right. The NamedParameterJdbcTemplate parameter has to be removed.
