### ISSUE TITLE
Fix active menu in angularjs branch

### ISSUE THREAD

**Issue by arey** [spring-projects/spring-petclinic#194]
Setting active class to nav menu from twitter bootstrap is not working.
There are 2 issues:
1. Home menu remains active all the time
2. Owners menu is never active

**Comment by mszarlinski** [comment]
Hi, I would like to fix it.

**Comment by arey** [comment]
Thanks for your help. Could you please work on it then submit a pull request?

**Comment by mszarlinski** [comment]
OK

**Comment by mszarlinski** [comment]
BTW can I replace `ng-route` with `ui-router` module? It is more powerful and elegant routing system, I could also benefit from that when fixing a navigation bar.

**Comment by arey** [comment]
angularjs branch has moved to https://github.com/spring-petclinic/spring-petclinic-angular1/issues/1
