### ISSUE TITLE
how to  make Spring @Transaction method call by the method within the same class??

### ISSUE THREAD

**Issue by GodIT** [spring-projects/spring-petclinic#195]
hello !
    Find so many web site ,no answer.

Can you help me??

 As mentioned on the stackoverflow.com website:
[http://stackoverflow.com/questions/3423972/spring-transaction-method-call-by-the-method-within-the-same-class-does-not-wo](url)

**Comment by arey** [comment]
You have to call the transactional method trough a TransactionInterceptor.
Starting from Spring 4.3, you may use self-injection: https://jira.spring.io/browse/SPR-8450 
In earlier release, you may inject the ApplicationContext then call a getBean()

**Comment by arey** [comment]
@GodIT I hope my answer could help you. I'll close this issue. Feel free to comment it.
