### ISSUE TITLE
Distributed PetClinic with Spring Cloud

### ISSUE THREAD

**Issue by mszarlinski** [spring-projects/spring-petclinic#198]
I would like to provide a "Spring Cloud" branch for the application to show how to split existing monolithic application into **microservices**. Distributed vesion would be based on a codebase from ["angularjs" branch](https://github.com/spring-projects/spring-petclinic/tree/angularjs) . What do you guys think?

**Comment by arey** [comment]
I Maciej. This could be a great idea but could you please wait one or two weeks? Indeed the angularjs branch will be move to another repository.

**Comment by mszarlinski** [comment]
Thanks for your replay. Actually I'm almost finished with a basic version built with Spring Cloud Config, Eureka, Hystrix and Zuul. Of course I can wait with a pull request for the new repository. By the time it is created, I should be ready with adjusted Docker setup. You can assign a task to me.

**Comment by dsyer** [comment]
You might want to look at #200 as well. That kind of modularization could be useful. if you are going to split the "monolith" (otherwise I can't see the point of introducing all the Spring Cloud stack).

**Comment by mszarlinski** [comment]
Hi Dave, thanks for your comment. I already did something similar with [Visit entity](https://github.com/mszarlinski/spring-petclinic/blob/spring-cloud/petclinic-visits-service/src/main/java/org/springframework/samples/petclinic/visits/domain/model/visit/Visit.java) when I was trying to define bounded contexts. And yes, I'm going to **split the monolith** :)

**Comment by arey** [comment]
Dave, you may see the Maciej's work here: https://github.com/spring-petclinic/spring-petclinic-microservices
Now that the Spring Cloud Petclinic has its own repo, we could close this question.

**Comment by mszarlinski** [comment]
@dsyer any comments and suggestions are certainly welcome :) I think after some time I will refresh microservices branch from this master (for example get rid of a thin service layer).
