### ISSUE TITLE
Branches renaming

### ISSUE THREAD

**Issue by vfedoriv** [spring-projects/spring-petclinic#201]
So, now boot-spring branch -> master,  master -> legacy, right ?
Dave, can you describe next changes for this project ?

**Comment by arey** [comment]
@dsyer I would like to know if Pivotal plan to maintain de legacy branch?

**Comment by vfedoriv** [comment]
Yea, today I practically finished work to extend functionality base repositories (insert/update/delete vets, pet types etc...) + REST-controllers.
[https://github.com/vfedoriv/spring-petclinic/tree/rest](url)
Pull this in legacy branch or... ?

**Comment by dsyer** [comment]
Yes please, if it was destined for the old master. I don't think we need to shut anything down. We just would like to change the emphasis a bit I think.

**Comment by arey** [comment]
See #205
