### ISSUE TITLE
Spring Petclinic organization

### ISSUE THREAD

**Issue by arey** [spring-projects/spring-petclinic#203]
Brian Dussault, the Director of the Spring engineering team, asked me to move the angularjs branch to another repository, outside of the [spring-projects](https://github.com/spring-projects) organisation that will be reserved to Pivotal employees.

I've created a brand new GitHub organisation called [spring-petclinic](https://github.com/spring-petclinic). You will find the [spring-petclinic-angular1](https://github.com/spring-petclinic/spring-petclinic-angular1).
The  [spring-petclinic](https://github.com/spring-petclinic) organisation has been created to host Spring Petclinic forks. Spring community members could have direct commit rights on it.

We may imagine other projects for React, Angular 2, Spring Cloud and so on. @nilshartmann, @mszarlinski you may take the lead on it. 

Feel free to join this organisation by asking trough this issue.

**Comment by mszarlinski** [comment]
Ok, I would like to push forward with AngularJS and Spring Cloud version. My goal is to polish AngularJS branch and setup a distributed version on top of it ✌️️On the other hand, I'm not familiar with ReactJS and I wonder how to reconcile that branch with upcoming Spring Cloud version.

**Comment by arey** [comment]
@mszarlinski I've invited you to the spring-petclinic organisation. Once accepted, I could give you permission to the spring-petclinc-angular1 project. You may work with feature branch and pull request or with direct commit, as you prefer.
For ReactJS, I was thinking about  @nilshartmann who already have a private repo.

**Comment by nilshartmann** [comment]
Hi,

even my React branch/fork is still heavy work in progress with a lot of improvements I'd be more than happy to share the code in this new organization.

Regards,
Nils

**Comment by arey** [comment]
Nils, I've just invited you to the spring-petclinic organisation. I've proposed too to David Syer.

**Comment by nilshartmann** [comment]
Hi Antoine, thanks for the invitation. Should I add a "spring-petclinic-reactjs" project with my reactjs branch?

**Comment by arey** [comment]
Yes you cloud. I think it will have a better visibility and you may be help by the community.

**Comment by nilshartmann** [comment]
I've added the new repository. Thanks again for your invitation!

**Comment by agrison** [comment]
Hello @arey is that still a thing? I found this link to this PR on [your blog](https://javaetmoi.com/2016/12/les-forks-de-spring-petclinic/), didn't see any other mention in the READMEs as to _how to join_ (is there an official way to ask, or someone specific to contact?).

I forked the Spring PetClinic to make it use [htmx](https://htmx.org), see: [agrison/spring-petclinic-htmx](https://github.com/agrison/spring-petclinic-htmx) and would be interested to know if it could be included there?

Some may also eventually want to participate and improve it.

**Comment by dsyer** [comment]
It's still a thing, and the HTMX version sounds interesting. Antoine might not see your comment unless you try and ping him directly (he's the org owner and therefore the only person who can invite you AFAIK).

**Comment by agrison** [comment]
Thank you for your answer @dsyer, much appreciated.
I will send him an email directly then.

**Comment by arey** [comment]
@agrison I've just answered to your email. Thanks for your contribution :)

@dsyer do you want I add you as owner of the org? For safety, I think it would be more appropriate to have two members in this role.

**Comment by dsyer** [comment]
Sure, thanks.
