### ISSUE TITLE
Has part of "MySQL Configuration" been removed? 

### ISSUE THREAD

**Issue by ShawnyXiao** [spring-projects/spring-petclinic#210]
In this project, I find a file like README in "src\main\resources\db\mysql\petclinic_db_setup_mysql.txt". Then I want to follow the steps in that file. but I can't find the specified files or directorys or statements, like:  "uncomment the mysql-connector from the Petclinic pom" (There is no this comment in pom), "executing the db/mysql/initDB.sq script" (There is no this script in that directory), "Open src/main/resources/spring/data-access.properties" (There is no this file), and so on...

If this part has been changed or removed, please update correlative documents.

**Comment by arey** [comment]
We may remove the petclinic_db_setup_mysql.txt. You now have to read the README.md in order to switch from HSQLDB to MySQL.

**Comment by ShawnyXiao** [comment]
I get it. Thank u~

**Comment by dsyer** [comment]
Fixed in 8b76a54
