### ISSUE TITLE
Proper documentation required ...

### ISSUE THREAD

**Issue by swapy** [spring-projects/spring-petclinic#221]
Spring petclinic previously had a really good [documentation](http://docs.spring.io/docs/petclinic.html) for beginners like me, but it`s outdated now. I have no idea on how it is working ... as it does not have proper documentation. Presentation attached is also very old one.

**_WITHOUT PROPER DOCUMENTATION(README) ITS NOT VERY DEVELOPER AND BEGINNER FRIENDLY._**
This documentation must have all howtos and how is it working in boot app...
Following can be some pointers....
1. Testing(Types of testing done)
2. Profiles
3. Internationalization
4. Validation
5. Explaining package structure.
6. SQL scripts
7. Caching
8. Templates
9. Application Configuration
10. JMX

 
I think documentation must also have a section of what is the difference between legacy spring app and this one: 

Following can be noted differences:

- Previously, app followed **3 layer architecture**, which is now outdated.(Why I don't know)
- Current package structure is also very VERY different, previously all entities were stored in `org.springframework.samples.petclinic.model`.
- Now, all settings are stored in application-* properties.
- Where did many things go.... it seems magic.... 
and so on....

Please make sure the documentation is very detailed like [this](http://docs.spring.io/docs/petclinic.html). but with much more details.

**Comment by KidPluto** [comment]
I am having the same issues.  Looking at the slide deck labelled "Data Access" it says "...inside web.xml...".  There is no web.xml, so am at a loss for what is happening here. 
I find this a great example and would love to be able to use it to better understand Spring MVC, ... .
Thx.

**Comment by arey** [comment]
@dsyer started to rework the outdated documentation in the [gh-pages](https://github.com/spring-projects/spring-petclinic/tree/gh-pages) branch. The result is published by GitHub at http://projects.spring.io/spring-petclinic/. It should replaced the [old doc](http://docs.spring.io/docs/petclinic.html) 

The main documentation (markdown syntax) remains into the [index.html](https://github.com/spring-projects/spring-petclinic/blob/gh-pages/index.html) file.
Anybody interested to refresh it could ask Dave.

**Comment by KidPluto** [comment]
Ok, a quick glance seems like it is more complete.  Will take a look at this.  Does "**gh**" stand for anything I should know?  Thanks.

**Comment by arey** [comment]
**gh** is just an acronym for GitHub pages

**Comment by KidPluto** [comment]
Nope, still can't find anything which is up-to-date.

**Comment by dsyer** [comment]
I think the README is adequate for most purposes, especially in combination with the many Spring Boot guides and tutorials that are out there. Closing as "won't fix".
