### ISSUE TITLE
Update Pet showing null null as first name and last name

### ISSUE THREAD

**Issue by GadiMahesh** [spring-projects/spring-petclinic#224]
1.when we click on Update Pet showing null null as first name and last name
2.we need show date format when enter date into Birth date column.
![updatepet](https://cloud.githubusercontent.com/assets/19890396/21808906/586ba5e8-d76b-11e6-9bde-5b7e210d8683.jpeg)

**Comment by dsyer** [comment]
Works for me. Can you try again with the code in master?

Please open a separate issue for the date format.

**Comment by evpaassen** [comment]
This is a duplicate of #207 and it has been fixed in #213.
