### ISSUE TITLE
Veterinarians tab showing null values on second visit

### ISSUE THREAD

**Issue by chrissiedeist** [spring-projects/spring-petclinic#227]
When I start the application and visit the veterinarians tab, it initially appears populated with data. When I then visit the home page and return to this tab, it appears populated with null values, as in the attached screenshot.

![screen shot 2017-01-20 at 9 54 49 am](https://cloud.githubusercontent.com/assets/4432186/22155847/92a9d2b0-def6-11e6-80b6-0c4cfbaefd3d.png)

There is nothing in the logs indicating that this request is even making it to the server (though the error tab still generates the (expected) exception `[Request processing failed; nested exception is java.lang.RuntimeException: Expected: ontroller used to showcase what happens when an exception is thrown] with root cause`

**Comment by fg78nc** [comment]
I have the same issue.

**Comment by dsyer** [comment]
It's the cache config, sorry. Fixed in c7657df.
