### ISSUE TITLE
Build is failing in Maven

### ISSUE THREAD

**Issue by Ajithkumar10** [spring-projects/spring-petclinic#233]
Im new to Java, please help me to resolve this error in eclipse after i cloned github

[ERROR] Failed to execute goal pl.project13.maven:git-commit-id-plugin:2.2.2:revision (default) on project spring-petclinic: .git directory is not found! Please specify a valid [dotGitDirectory] in your pom.xml -> [Help 1]

**Comment by arey** [comment]
I think toy have download the repository from GitHub. The zip archive does not contain any .git directory.
@dsyer maybe we should set the ```failOnNoGitDirectory```property of the git-commit-id-plugin  to false?

**Comment by dsyer** [comment]
Sure, if that's an option, let's set it.

**Comment by Ajithkumar10** [comment]
Please let me know when can I download latest version which has this fix.

**Comment by arey** [comment]
@Ajithkumar10 you may test

**Comment by Ajithkumar10** [comment]
Thank alot...I'll test and update

**Comment by Ajithkumar10** [comment]
It's working now..Thanks all!
