### ISSUE TITLE
work with MSM

### ISSUE THREAD

**Issue by Clcanny** [spring-projects/spring-petclinic#241]
I would like to ask, how to make petclinic work with msm?

**Comment by Clcanny** [comment]
Actually, the question is where is context.xml?
I can't find that file, so I can't configure tomcat8.

**Comment by arey** [comment]
Spring Petclinic is packaged as an executable JAR. Based on Spring Boot, it uses Tomcat as an embedded servlet container. Thus there is no web.xml. 
For traditional deployment (a war into a web container), please refer to the manual: http://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-traditional-deployment

**Comment by Clcanny** [comment]
https://gist.github.com/Clcanny/8b186b083130faba7bc17f8e0928cc7c
my solution working with docker
