### ISSUE TITLE
Shouldn't there be a licence on the repo?

### ISSUE THREAD

**Issue by lesv** [spring-projects/spring-petclinic#260]

**Comment by arey** [comment]
You're right @lesv.
Java classes of the Spring Petclinic are referencing the Apache 2.0 licence: 
https://github.com/spring-projects/spring-petclinic/blob/master/src/main/java/org/springframework/samples/petclinic/model/BaseEntity.java
Thus we could add a licence at the root of this repo and in the readme.md.
Moreover, the Spring Framework is released under version 2.0 of the Apache License.
@dsyer could you confirm ?

**Comment by dsyer** [comment]
Spring projects don't normally copy the license bytes into their repo, but I guess I don't really care. A link in the README and a `<license>` in the pom should do it.

**Comment by arey** [comment]
Thanks Dave. I've pushed the #265
