### ISSUE TITLE
mvn tomcat7:run fails

### ISSUE THREAD

**Issue by earlbingham** [spring-projects/spring-petclinic#27]
cpepool6cmts1-62:SpringExamples earlbingham$ mvn tomcat7:run
[INFO] Scanning for projects...
Downloading: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloading: http://repo1.maven.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloaded: http://repo1.maven.org/maven2/org/apache/maven/plugins/maven-metadata.xml (12 KB at 110.0 KB/sec)
Downloaded: http://repo1.maven.org/maven2/org/codehaus/mojo/maven-metadata.xml (22 KB at 170.1 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.552s
[INFO] Finished at: Wed Aug 07 21:00:47 PDT 2013
[INFO] Final Memory: 3M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'tomcat7' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/earlbingham/.m2/repository), central (http://repo1.maven.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by gomzy27** [comment]
I am getting the same error can you pls help me with it.

**Comment by arey** [comment]
Hi @gomzy27. Thanks to Spring Boot, you don't need to use the tomcat plugin for maven.
Just :
```
./mvnw spring-boot:run
```

**Comment by jobingo** [comment]
Have something similar..I will appreciate any help

[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building simple 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.220 s
[INFO] Finished at: 2017-05-15T11:33:52-06:00
[INFO] Final Memory: 18M/1104M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project simple: Could not resolve dependencies for project Simple:simple:war:1.0-SNAPSHOT: Failed to collect dependencies at Simple:taglib:jar:1.0-SNAPSHOT: Failed to read artifact descriptor for Simple:taglib:jar:1.0-SNAPSHOT: Could not find artifact Simple:simple-app:pom:1.0-SNAPSHOT -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by arey** [comment]
@jobingo are you building petclinic or another maven project?

**Comment by jobingo** [comment]
another maven project

**Comment by jobingo** [comment]
petclinic looks similar to my project with regards to the error...I am using maven build and tomcat7.0.77

**Comment by arey** [comment]
I'm sorry but it's not the right place for such kind of question. Please go to Stackoverflow.
