### ISSUE TITLE
Redundant Javadoc for getters and setters

### ISSUE THREAD

**Issue by rillig-nm** [spring-projects/spring-petclinic#273]
At least in the `Visit` class, the Javadoc for the fields, getters and setters is very verbose and completely redundant.

The Javadoc on the class and on the constructor are helpful and should remain. All others should be removed.

If the same issue also affects other classes, these should be cleaned up as well.

**Comment by arey** [comment]
You're right. It looks like generated javadoc.

**Comment by dsyer** [comment]
Closed in #276
