### ISSUE TITLE
No way to add new pet to owner

### ISSUE THREAD

**Issue by pblanton** [spring-projects/spring-petclinic#279]
The birthdate field format in the Add Pet screen is impossible to figure out without some hint. This makes it impossible to add a new pet to an owner.

**Comment by arey** [comment]
Maybe adding an HTML placeholder attribute could help?
```
<input class="form-control" type="text" id="birthDate" name="birthDate" "placeholder="YYYY-MM-DD">
```

**Comment by dsyer** [comment]
Sounds like a plan. PR anyone?

**Comment by snicoll** [comment]
Closing in favour of PR #303
