### ISSUE TITLE
Add Generic Cucumber Feature Test

### ISSUE THREAD

**Issue by josepharuja** [spring-projects/spring-petclinic#284]
Currently all the test are based around spring framework.. we want generic tests to test the feature using cucumber so that we can start the application as test using generic frameworks that will increase the acceptability of framework into wider audience..

**Comment by dsyer** [comment]
While cucumber is an excellent tool, I'm not sure the cucumber community counts as a "wider audience". If you would like to create some cucumber tests and maintain them in your own work, or in a project in the community org (https://github.com/spring-petclinic), please go ahead and we can list it in the community docs.

**Comment by josepharuja** [comment]
Thanks David... Will go ahead and add that to pet-clinic..
