### ISSUE TITLE
issue with wro4j

### ISSUE THREAD

**Issue by sarlv** [spring-projects/spring-petclinic#295]
When I try to install project `./mvnw spring-boot:run` I am getting this error:

`[ERROR] Failed to execute goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run (default) on project spring-petclinic: Execution default of goal ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run failed: An API incompatibility was encountered while executing ro.isdc.wro4j:wro4j-maven-plugin:1.8.0:run: java.lang.ExceptionInInitializerError: null
`

**Comment by felixbarny** [comment]
I have the same issue. How did you resolve this? Seems only to be a problem when using Java 9.

**Comment by mdiloreto16** [comment]
Also been having this issues, has it been resolved yet?

**Comment by arey** [comment]
Wro4j wil support Java 9 in its next release, the 1.8.1 one. Unfortunately, we are waiting the release.
See https://github.com/wro4j/wro4j/issues/1039

**Comment by mdiloreto16** [comment]
thanks for the link, I actually just found that issue thread as I recieved your message. I added that to the wro4j dependencies in my pom file and it fixed the issue. Thanks!
