### ISSUE TITLE
create spring boot 1.x branch

### ISSUE THREAD

**Issue by saturnism** [spring-projects/spring-petclinic#300]
Trying to use Spring Petclinic w/ Spring Boot 1.5, but the master head is on 2.0 snapshot now. It would help if the repo has a 1.x branch that kept the older version of this that users can check out to :)

**Comment by joedayz** [comment]
Ok. that's the problem then:

'dependencies.dependency.version' for org.webjars:webjars-locator:jar is missing. @ line 85, column 17.

**Comment by snicoll** [comment]
@joedayz not really, just a sync issue that is fixed now, see #305

**Comment by dsyer** [comment]
I created a tag (not a branch) at the last point where we use Boot 1.5. There's no intention to support it, so a branch seems like the wrong label.
