### ISSUE TITLE
why not upgrade springboot2.0 and using springwebflux?

### ISSUE THREAD

**Issue by boboyada** [spring-projects/spring-petclinic#313]
springboot2.0 is out.
and spring-webflux is readly!
why not upgrade springboot2.0 and using springwebflux?

**Comment by snicoll** [comment]
@boboyada `master` already uses Spring Boot 2 for quite some time now. Migrating WebFlux requires a use case for this and petclinic has none that would justify a migration to WebFlux. 

Spring MVC isn't going anywhere and remains a first class citizen in Spring Boot 2.
