### ISSUE TITLE
problem with db connection

### ISSUE THREAD

**Issue by ormam** [spring-projects/spring-petclinic#321]
Can somebody please explain step by step how do i change the data-base to mysql for the following command

docker run -e MYSQL_ROOT_PASSWORD=petclinic -e MYSQL_DATABASE=petclinic -p 3306:3306 mysql:5.7.8

because every time i try to change something in the files the "mvn package" i get a build fail.
Thanks

**Comment by trisberg** [comment]
See https://github.com/spring-projects/spring-petclinic/pull/323

**Comment by snicoll** [comment]
Thanks @trisberg. 

@ormam thank for the report, this is going to be taken care of in #323
