### ISSUE TITLE
petclinic.jmx

### ISSUE THREAD

**Issue by amruthapbhat** [spring-projects/spring-petclinic#329]
hi,

Could you please let me know what specific changes needs to be done if iam running jmeter for a petclinic application in one server

**Comment by arey** [comment]
Hi, you have to remove some .html extensions. See details in my PR https://github.com/arey/spring-petclinic/commit/d35b0c6e697a02f5762053d306d6a70de9f79ff4

**Comment by amruthapbhat** [comment]
<stringProp name="Argument.name">PETCLINIC_HOST</stringProp>
 <stringProp name="Argument.value"></stringProp>

In the second row i would have to mention the **http://IP address:port/petclinic** value right?

**Comment by arey** [comment]
In the pre-declared variable of the Test Plan, you may set the host and the port of the petclinic application trough the PETCLINIC_HOST and the PETCLINIC_PORT
For a remote deployment, you may change PETCLINIC_HOST from localhost to another hostname or a domain name.

**Comment by snicoll** [comment]
Closing in favour of PR #330
