### ISSUE TITLE
Enable caching of static resources

### ISSUE THREAD

**Issue by arey** [spring-projects/spring-petclinic#331]
The ```Cache-Control``` HTTP header is not set to static resources as ```/webjars/jquery/2.2.4/jquery.min.js```
We may enable caching of static resources by setting the ```spring.resources.cache.cachecontrol.max-age``` property. Maybe in a ```production``` profile?

**Comment by snicoll** [comment]
I don't think a `production` profile is the right naming for something like Petclinic. We need to demonstrate features that do make sense with regard to the target use cases.

Having said that, this certainly isn't one of my expertise area so I am paging @bclozel for a more informed opinion.

**Comment by bclozel** [comment]
A `spring.resources.cache.cachecontrol.max-age` property sounds right.
If devtools is on the classpath, this property should be overridden by default when developing the application, so no need for a production profile.

**Comment by arey** [comment]
Devtools is on the classpath, but with a runtime scope and not as an optional dependency. Does it matter?

**Comment by snicoll** [comment]
It doesn't for the feature @bclozel described. Having it with optional is the canonical way with Maven though so I've fixed that in 415bd73

**Comment by snicoll** [comment]
Closing in favour of PR #332
