### ISSUE TITLE
Document how to build and run petclinic in an IDE

### ISSUE THREAD

**Issue by devayushk** [spring-projects/spring-petclinic#341]

**Comment by vfedoriv** [comment]
here .less version:
https://github.com/spring-projects/spring-petclinic/blob/master/src/main/less/petclinic.less
you can get .css version (if you need) here:
https://github.com/spring-petclinic/spring-petclinic-angular/blob/master/src/assets/css/petclinic.css

**Comment by snicoll** [comment]
@devayushk I don't really understand what you mean given the lack of description but CSS are generated by the maven build. Let's use this as an opportunity to improve the documentation.

**Comment by dsyer** [comment]
There was already some documentation on Eclipse STS. I tidied it up a bit (b982e66). If someone wants to add the IntelliJ equivalent that would help.

**Comment by snicoll** [comment]
Closing in favour of PR #358
