### ISSUE TITLE
Dockerfile for example usage?

### ISSUE THREAD

**Issue by Lewiscowles1986** [spring-projects/spring-petclinic#348]
I was asked to put this into a dockerfile as part of a coding challenge. I've completed it and wondered if the application Dockerfile would be of use to anyone?

I think further enhancements could be using environment variables for DB connection information because #160 mentions CloudFoundry. It's more native for Docker to use ENV vars for easily changable information.

I also have edits for the docker-compose.yml, the pom.XML (to generate WAR archive / fat JAR). which alongside the multi-stage build gives me a 122MB deploy (36.9MB is the .Jar archive)

Happy to contrib docs on using, uses standard openJDK docker images.

**Comment by Lewiscowles1986** [comment]
Should this use #349 JDK/JRE 10 or stick with JDK/JRE 8?

JDK/JRE 10 is 334MB with 39MB .Jar archive

**Comment by snicoll** [comment]
We've already discussed the use of docker here and the proposal was declined, see #339 - please consider searching the issue tracker before opening a new issue.

**Comment by Lewiscowles1986** [comment]
please consider deleting the docker-compose.yml then as it's essentially useless and uses docker.
