### ISSUE TITLE
Missing artifact org.eclipse.jetty.samples:dandelion-jsp:jar:1.1.2-SNAPSHOT

### ISSUE THREAD

**Issue by abellis** [spring-projects/spring-petclinic#356]
Eclipse build getting error
Missing artifact org.eclipse.jetty.samples:dandelion-jsp:jar:1.1.2-SNAPSHOT

**Comment by snicoll** [comment]
Petclinic doesn't use such artifact so it looks like this was reported by mistake. If I've missed something, we can reopen if you provide more details about what you think is a problem here.
