### ISSUE TITLE
Cannot run application on EC2 instance

### ISSUE THREAD

**Issue by arun-gupta** [spring-projects/spring-petclinic#368]
Tried to run this application on an EC2 instance as:

```
git clone https://github.com/spring-projects/spring-petclinic.git
cd spring-petclinic
./mvnw package
java -jar target/*.jar --server.port=80
```

The application was accessible at http://localhost:80 but accessing it using `http://<public-ip>` gives the following error:

```
{"Message":"User: anonymous is not authorized to perform: es:ESHttpGet"}
```

**Comment by dsyer** [comment]
That doesn’t look like a response from a spring app. Is it from AWS?

**Comment by arun-gupta** [comment]
PEBKAC
