### ISSUE TITLE
h4s-spring-petclinic-reactjs :: com.hdivsecurity dependency

### ISSUE THREAD

**Issue by ranjit909** [spring-projects/spring-petclinic#379]
Missing artifact com.hdivsecurity:hdiv-for-services:jar:1.7.51-SNAPSHOT

<dependency>
			<groupId>com.hdivsecurity</groupId>
			<artifactId>hdiv-for-services</artifactId>
			<version>1.7.51-SNAPSHOT</version>
		</dependency>

**Comment by snicoll** [comment]
This project is not handled here but in the [Spring Petclinic organization](https://github.com/spring-petclinic), see https://github.com/spring-petclinic/spring-petclinic-reactjs
