### ISSUE TITLE
How to access to the in-memory hsqldb for pet clinic

### ISSUE THREAD

**Issue by aCodeRancher** [spring-projects/spring-petclinic#384]
Hi, in IntelliJ, I tried to create a db connection with url: jdbc:hsqldb:mem:hsqldb (in-memory).
But when I started the pet clinic application, I don't see those Pets, Owners... table in this database.
What is the exact url to access to this in-memory hsql db?

**Comment by snicoll** [comment]
@aCodeRancher this repository is not meant to answer questions. For general purpose questions about Spring Boot, please ask on StackOverflow.
