### ISSUE TITLE
Maven wrapper doesn't work with spaces in quotes

### ISSUE THREAD

**Issue by Eskibear** [spring-projects/spring-petclinic#404]
#### `mvnw` doesn't work
<img width="844" alt="Screen Shot 2019-03-28 at 10 37 14 AM" src="https://user-images.githubusercontent.com/2351748/55125762-aab39580-5145-11e9-98e9-5ca76d1710e8.png">

#### `mvn` works for spring-petclinic
<img width="592" alt="Screen Shot 2019-03-28 at 10 44 56 AM" src="https://user-images.githubusercontent.com/2351748/55125976-8e642880-5146-11e9-8abf-3ec2c055785b.png">

#### `mvnw` in [another spring project](https://github.com/Microsoft/todo-app-java-on-azure) works for it.
<img width="625" alt="Screen Shot 2019-03-28 at 10 42 39 AM" src="https://user-images.githubusercontent.com/2351748/55125923-50ff9b00-5146-11e9-8f77-5a1b22311758.png">

**Comment by snicoll** [comment]
@Eskibear we don't need an issue and a PR. A PR is enough.

Closing in favour of #405
