### ISSUE TITLE
"Your prefered IDE" does not include Visual Code

### ISSUE THREAD

**Issue by iulian-radu-at** [spring-projects/spring-petclinic#421]
Hi,

In Readme, the section "Your prefered IDE" should also include [Visual Code](https://code.visualstudio.com/) as VC displays a link to this github repo in its Java Overview page.

Cheers,
Iulian

**Comment by dsyer** [comment]
I added it to the bullet list in 912d2ad. Pull request more than welcome, if you have specific instructions for how to run the app in VS Code.
