### ISSUE TITLE
Spring Boot 2.2 upgrade

### ISSUE THREAD

**Issue by arey** [spring-projects/spring-petclinic#422]
According to the issue https://github.com/spring-projects/spring-boot/issues/14736 and @dsyer's comment into the PR https://github.com/spring-projects/spring-petclinic/pull/360, both `junit-jupiter-engine` and `mockito-junit-jupiter` artifacts could be removed from the `pom.xml`. Those Junit5 dependencies has been added to the Spring Boot Starter Test starting to the version 2.2.0.M3.

**Comment by snicoll** [comment]
I missed this one (thanks @dsyer), `master` has been upgraded to SB 2.2
