### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by sraghu-rs** [spring-projects/spring-petclinic#424]
Build failed with error message. Can you please advice me on how to resolve this?

[ERROR] Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.4.RELEASE:build-info (default) on project spring-petclinic: Execution default of goal org.springframework.boot:spring-boot-maven-plugin:2.1.4.RELEASE:build-info failed: Unable to load the mojo 'build-info' in the plugin 'org.springframework.boot:spring-boot-maven-plugin:2.1.4.RELEASE' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: org/springframework/boot/maven/BuildInfoMojo : Unsupported major.minor version 52.0

**Environment details**

- openjdk version "1.8.0_212"
- OpenJDK Runtime Environment (build 1.8.0_212-b04)
- OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
- CentOS Linux release 7.6.1810 (Core)

**Comment by ShreyAgarwal11** [comment]
Try to run maven clean and then maven install and after that start your spring boot application if that work then most probably your maven file has gone corrupt. To solve that simply locate your .m2 folder and delete it then again go to your project and click maven install after the installation run the project, the project should now run.

**Comment by ShreyAgarwal11** [comment]
Sorry a correction if maven clean and maven install **does not** work then.......

**Comment by snicoll** [comment]
@sraghu-rs your environment is not using Java 8 (you could check that by running `mvn -v`). Searching for the exception message first would have probably lead you to [this SO thread](https://stackoverflow.com/questions/22489398/unsupported-major-minor-version-52-0)
