### ISSUE TITLE
petclinic.css Not found

### ISSUE THREAD

**Issue by Subhendu-luv** [spring-projects/spring-petclinic#434]
GET http://127.0.0.1:8080/resources/css/petclinic.css net::ERR_ABORTED 404

**Comment by snicoll** [comment]
@Subhendu-luv please review [the readme](https://github.com/spring-projects/spring-petclinic#steps). CSS files are generated by the build, you have instructions for STS and IJ.

**Comment by elab** [comment]
see also #232
