### ISSUE TITLE
Consider removing spring-java-format-maven-plugin

### ISSUE THREAD

**Issue by kdvolder** [spring-projects/spring-petclinic#519]
The presence of that plugin results in the dreaded 'plugin execution not covered by lifecycle error' in Eclipse workspace.

Consumers of the spring-perclinic sample  (i.e users who want just want to explore the example code) probably do not care for the formatting validation so its probably best not to force this on them.

If you want to keep the plugin regardless, then perhaps consider adding this extra (yuck) XML to the pom instead to disable it inside of Eclipse:

```
    <pluginManagement>
    	<plugins>
    		<!--This plugin's configuration is used to store Eclipse m2e settings only. It has no influence on the Maven build itself.-->
    		<plugin>
    			<groupId>org.eclipse.m2e</groupId>
    			<artifactId>lifecycle-mapping</artifactId>
    			<version>1.0.0</version>
    			<configuration>
    				<lifecycleMappingMetadata>
    					<pluginExecutions>
    						<pluginExecution>
    							<pluginExecutionFilter>
    								<groupId>
    									io.spring.javaformat
    								</groupId>
    								<artifactId>
    									spring-javaformat-maven-plugin
    								</artifactId>
    								<versionRange>
    									[0.0.17,)
    								</versionRange>
    								<goals>
    									<goal>validate</goal>
    								</goals>
    							</pluginExecutionFilter>
    							<action>
    								<ignore></ignore>
    							</action>
    						</pluginExecution>
    					</pluginExecutions>
    				</lifecycleMappingMetadata>
    			</configuration>
    		</plugin>
    	</plugins>
    </pluginManagement>
```

**Comment by snicoll** [comment]
Thanks for the suggestion but we're certainly not going to remove a plugin because Eclipse complains about it. We've done something similar to your suggestion in other projects that was overlooked here.

**Comment by snicoll** [comment]
I don't see any presence of this plugin anywhere so I am a bit surprised it isn't a problem in other projects. Have I overlooked something @dsyer?

**Comment by kdvolder** [comment]
> Thanks for the suggestion but we're certainly not going to remove a plugin because Eclipse complains about it. 

Understandable. Thanks for considering it. And thanks for adding the m2e cruft to the pom instead. It's a real shame that you have to do this. But unfortunately m2e decided to be real pedantic and complain about any sort of plugin it 'doesn't understand'. There's isn't much we can do about that unfortunately. So all things considered adding that cruft seems like the right compromise.
