### ISSUE TITLE
Failed to execute database script; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection

### ISSUE THREAD

**Issue by raovikas** [spring-projects/spring-petclinic#53]
I am trying to switch from hsql to MySQL in the spring petclinic sample application. Can someone show me what I am doing wrong?

I followed the instructions in the petclinic_db_setup_mysql.txt file, and confirmed that the database was created correctly in mysql, but I am getting the following error when I try to run the application on tomcat 7 from within eclipse: 

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.jdbc.datasource.init.DataSourceInitializer#0': Invocation of init method failed; nested exception is org.springframework.jdbc.datasource.init.UncategorizedScriptException: Failed to execute database script; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Could not get JDBC Connection; nested exception is com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown database 'petclinic'

**Comment by michaelisvy** [comment]
Hi,
indeed the database can only be created automatically when using an in-memory database such as HSQL. Happy you could solve your issue.
