### ISSUE TITLE
there is none verification of dates

### ISSUE THREAD

**Issue by viruslemon** [spring-projects/spring-petclinic#593]
Date visit must be greater than birth date of pet.
![Captura](https://user-images.githubusercontent.com/7074515/78501810-c0e33100-775d-11ea-85f2-bcced1d17bdd.PNG)

**Comment by yurimokhna** [comment]
https://github.com/yurimokhna/spring-petclinic/commit/5e153c1f4eb0658018317744e806ccc3bd123fa2

**Comment by yurimokhna** [comment]
![PetClinic](https://user-images.githubusercontent.com/60264049/79670151-a2ebe680-81c9-11ea-874d-69ef93855490.png)
