### ISSUE TITLE
Add support for Postgres

### ISSUE THREAD

**Issue by dmadunic** [spring-projects/spring-petclinic#636]
in addition to h2, Petclinic app comes with support for mysql, it would be nice to have similar support for the second (maybe first ;-)) most popular open source database Postgres.

Support can be done along the same lines as the one for mysql, namely to add the following files and folders:
+ resources/
    - application-postgres.properties
    + db/
        + postgres/
            - data.sql
           - schema.sql

And finally, posgres jdbc driver should be added to the runtime dependencies in pom.xml

I have also attached to this issue all of the above files, for review.

[resources.zip](https://github.com/spring-projects/spring-petclinic/files/4829935/resources.zip)
schema.sql

**Comment by arey** [comment]
@dmadunic if you are interested, to prepare a Pull Request, you could look at the legacy version [spring-petclinic/spring-framework-petclinic](https://github.com/spring-petclinic/spring-framework-petclinic) that support PosgreSQL (see the [readme.md](https://github.com/spring-petclinic/spring-framework-petclinic/blob/master/readme.md))

**Comment by arey** [comment]
Ok great. Before that wait a response from @dsyer or @snicoll

**Comment by snicoll** [comment]
Feel free to submit a PR and we can take it from there.

**Comment by nroi** [comment]
I'd like to revive this topic. It's been over a year since the last reply, so I hope it's ok that I just went ahead and submitted a PR.

**Comment by lynchmaniac** [comment]
@nroi what a synchronicity, I just also posted a PR too on the same subject. :smiley: 

Cool, hoping the code is merged.

**Comment by nroi** [comment]
@lynchmaniac aah, what are the chances, after more than a year of silence, two PRs are posted just 3 minutes apart :smile:

**Comment by dsyer** [comment]
Resolved via #878
