### ISSUE TITLE
HTTP Status 404 – Not Found error while loading application web page

### ISSUE THREAD

**Issue by ashish1586** [spring-projects/spring-petclinic#647]
HI,

i have created a docker image and i am running it as a container on my machine. it says that my docker container is running but i get below error when i try to access web page 

http://35.232.129.102:8084/petclinic/

HTTP Status 404 – Not Found
Type Status Report

Description The origin server did not find a current representation for the target resource or is not willing to disclose that one exists.

Apache Tomcat/9.0.36

I have used below github repository for my job in jenkins through which i am generating my war file.

https://github.com/ashish1586/petclinic.

I have given below content in my Dockerfile-

FROM tomcat
ADD myapp.war /usr/local/tomcat/webapps/
EXPOSE 8080
CMD ["catalina.sh", "run"]

It would be really very helpful if anybody can look into my issue.

**Comment by snicoll** [comment]
Sorry but this issue tracker is not meant to provide support. Please follow-up on StackOverflow for questions.
