### ISSUE TITLE
spring-javaformat-maven-plugin execution not covered by lifecycle execution

### ISSUE THREAD

**Issue by mirslavo** [spring-projects/spring-petclinic#651]
pom.xml shows error in line 144 (<execution>):
"Plugin execution not covered by lifecycle configuration: io.spring.javaformat:spring-javaformat-maven-plugin:0.0.22:validate (execution: default, phase: validate)"

seems fixable by adding <pluginManagement>:
https://stackoverflow.com/questions/6352208/how-to-solve-plugin-execution-not-covered-by-lifecycle-configuration-for-sprin

**Comment by snicoll** [comment]
That's a warning introduced by Eclipse, most probably a false positive. I am not using Eclipse but perhaps @dsyer knows?

**Comment by dsyer** [comment]
The javaformat plugin doesn't have m2e metadata in the jar, so if there's an issue probably it needs to be addressed there: https://github.com/spring-io/spring-javaformat. On the other hand, I use Eclipse and I don't see any warnings. :shrug:

**Comment by dsyer** [comment]
See spring-io/spring-javaformat#224

**Comment by dsyer** [comment]
According to comments in the javaformat tool, you need to install the eclipse plugin.
