### ISSUE TITLE
[ERROR] Could not find goal

### ISSUE THREAD

**Issue by hifzurr** [spring-projects/spring-petclinic#652]
Waiting for Jenkins to finish collecting data
[ERROR] Could not find goal '' in plugin org.codehaus.mojo:findbugs-maven-plugin:3.0.5 among available goals check, findbugs, gui, help -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoNotFoundException
[JENKINS] Archiving /var/lib/jenkins/workspace/petclinic_project/petclinic_CI_job/pom.xml to org.springframework.samples/spring-petclinic/4.2.5-SNAPSHOT/spring-petclinic-4.2.5-SNAPSHOT.pom
channel stopped
Finished: FAILURE

**Comment by hifzurr** [comment]
How to resolve this issue?

**Comment by snicoll** [comment]
@hifzurr this issue tracker is not meant to provide support for your project. Please follow-up on StackOverflow for questions.
