### ISSUE TITLE
petclinic.css does not exist

### ISSUE THREAD

**Issue by guochengjun1993** [spring-projects/spring-petclinic#653]
Hi there, the styling of the site displaying incorrectly, Chrome debug console shows that request for petclinic.css was failed with an error code of 404, and i looked through both my local and online repository, and I couldn't find the file in path "/resources/css/petclinic.css". Could you guys provide the css file please? Thanks.
The Chrome debug console screenshot: 
![a8be52db4fa6abc623f429c3235121e](https://user-images.githubusercontent.com/31728935/88452429-31d76180-ce91-11ea-80c0-d64034a228fc.png)

**Comment by ebiggerr** [comment]
The petclinic.css should be generated from the less file which located at "webapp\resources\less\petclinic.less". Mine here, the styling is working. Are you using Jetty or Tomcat as the server? Changing it to Jetty might solve this issue.

**Comment by micheljr** [comment]
What you can also do is create a css directory in the static.resources directory and paste the less files in there.
This worked for me!

**Comment by guochengjun1993** [comment]
> The petclinic.css should be generated from the less file which located at "webapp\resources\less\petclinic.less". Mine here, the styling is working.

Thank you for the reply, when I try to compile the less files in vs code, there was this error came up ".label-success is undefined in file ...spring-petclinic-main\src\main\less\petclinic.less line no. 181", and I've searched the whole project, there is no other definition for ".label-success", is the less file complete?

**Comment by guochengjun1993** [comment]
> What you can also do is create a css directory in the static.resources directory and paste the less files in there.
> This worked for me!

I tried this method, it didn't work for me, the error code is 404, my IDE is vs code, could it be vs code issue?

**Comment by vkbvipul** [comment]
I am also facing same issue.
Please assist.
Have tried options suggested but still no luck.

**Comment by ebiggerr** [comment]
The "wro4j" plugin is responsible for the css file generating from less file. Please check whether the the plugin is in the **pom.xml** 
One thing to note that, this plugin requires Java 9 and above since **wro4j 1.0.0** and the latest version of spring petclinic uses **wroj 1.8.0** Therefore, changing JDK to version 9 and above should help in solving this issue.

**Comment by ebiggerr** [comment]
> 
> 
> I am also facing same issue.
> Please assist.
> Have tried options suggested but still no luck.



> 
> 
> Hi there, the styling of the site displaying incorrectly, Chrome debug console shows that request for petclinic.css was failed with an error code of 404, and i looked through both my local and online repository, and I couldn't find the file in path "/resources/css/petclinic.css". Could you guys provide the css file please? Thanks.

CSS files are generated from the Maven build, using the less file in **spring-petclinic\src\main\less\*.less**
There are two ways to generate the resources needed for the styling.

-Using local maven executable binary
If you have already installed maven in your computer, you can just `cd` to the project directory using the terminal available in your IDE or using cmd/Terminal depending on (Windows/Mac/Linux) 
Example : `cd C:\Users\xxx\projects\spring-petclinic`
`C:\Users\xxx\projects\spring-petclinic>mvn generate-resources`

-using the maven wrapper
run the `mvnw`  available in the project directory. using command `./mvnw generate-resources` . 

After the build success, you can run the spring petclinic application and access it from localhost:8080 and the styling will be working

**Comment by vkbvipul** [comment]
css gets generated using wro4j.
If you have installed mvn command line tool then go to project directory and execute command "mvn wro4j:run". Can refer https://stackoverflow.com/questions/3448648/how-do-i-run-a-specific-goal-with-a-particular-configuration-in-a-maven-plugin-w
If you are using eclipse right click on project -> Run As -> click Maven Build...
On "Goals" input field enter wro4j:run
Click Apply then Run.

My issue for css was resolved using same steps.

**Comment by snicoll** [comment]
As others have indicated, the CSS is generated as part of the build. If you'r running petclinic from an IDE, [the readme provides some more explanations](https://github.com/spring-projects/spring-petclinic#steps).
