### ISSUE TITLE
maven-compiler-plugin:3.0:testCompile (default-testCompile)

### ISSUE THREAD

**Issue by palanivel91** [spring-projects/spring-petclinic#654]
Waiting for Jenkins to finish collecting data
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-war-plugin:2.3:war (default-war) on project spring-petclinic: Error assembling WAR: webxml attribute is required (or pre-existing WEB-INF/web.xml if executing in update mode) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[JENKINS] Archiving /home/jenkins-slave-01/workspace/DevOps_Demo/Ex-4_jave_project/pom.xml to org.springframework.samples/spring-petclinic/4.2.5-SNAPSHOT/spring-petclinic-4.2.5-SNAPSHOT.pom
channel stopped
Finished: FAILURE

**Comment by snicoll** [comment]
Petclinic doesn't use `war` packaging type. If you're looking for support, please ask questions on StackOverflow.
