### ISSUE TITLE
Browse pets by type

### ISSUE THREAD

**Issue by ghost** [spring-projects/spring-petclinic#659]
Add a logic that enables to search pets by type.  Possible output view from this search can be seen in the attached file pet search.jpg. 
![pet search](https://user-images.githubusercontent.com/10178734/90551844-9ccb3e00-e19a-11ea-8327-bbaeeb9da771.jpg)

**Comment by snicoll** [comment]
Thanks for the suggestion but we have no intention to expand the scope of this project at this point.
