### ISSUE TITLE
Fix Java code smells detected by SonarQube

### ISSUE THREAD

**Issue by abhijaykumar** [spring-projects/spring-petclinic#662]
When I ran SonarQube on the Java project, it reported 16 code smells, most of which can be easily fixed to follow Java static code analysis rules as per https://rules.sonarsource.com/java/.

- src/.../samples/petclinic/system/CacheConfiguration.java Remove useless curly braces around statement

- src/.../samples/petclinic/vet/VetController.java Rename "vets" which hides the field declared at line 33.
Rename "vets" which hides the field declared at line 33.

- src/.../samples/petclinic/vet/VetRepository.java Remove the declaration of thrown exception 'org.springframework.dao.DataAccessException' which is a runtime exception.

- src/.../samples/petclinic/vet/Vets.java Rename field "vets"

- src/.../samples/petclinic/visit/VisitRepository.java Remove the declaration of thrown exception 'org.springframework.dao.DataAccessException' which is a runtime exception.

- src/.../samples/petclinic/model/ValidatorTests.java Use assertThat(actual).hasToString(expectedString) instead.

- src/.../samples/petclinic/service/ClinicServiceTests.java Use isNotZero() instead. Use assertThat(actual).hasSize(expected) instead.

**Comment by snicoll** [comment]
Let's follow up on the PR you've created. Closing in favour of PR #663.
