### ISSUE TITLE
Replace persistence entities with simple DTO objects.

### ISSUE THREAD

**Issue by mahdieha** [spring-projects/spring-petclinic#667]
If we using a persistence object (@Entity) as an argument of a method annotated with @RequestMapping, it is possible that the end-user can change the content of unexpected fields in the database, which eventually lead to a critical bug. 

For example on the below controllers, we need to replace entities with a simple Dto:
1. OwnerController
2. PetController
3. VisitController

**Comment by arey** [comment]
SonarQube references this security flaw: https://rules.sonarsource.com/java/tag/spring/RSPEC-4684

We have encountered this issue on other forks of Spring Petclinic (ie. https://sonarcloud.io/project/issues?id=spring-petclinic_spring-framework-petclinic&open=AWq4K0FjEGMyMe6L0asK&resolved=false&types=VULNERABILITY)

**Comment by pedsf1968** [comment]
> If we using a persistence object (@entity) as an argument of a method annotated with @RequestMapping, it is possible that the end-user can change the content of unexpected fields in the database, which eventually lead to a critical bug.
> 
> For example on the below controllers, we need to replace entities with a simple Dto:
> 
> 1. OwnerController
> 2. PetController
> 3. VisitController

Yes @mahdieha for me we must isolate @Controller from @Repository by using @Service and DTO.
Controller call Service using DTO and Service call Repository using @Entity

**Comment by pedsf1968** [comment]
I have send a pull request with the feature branch 
Feature/implement services

**Comment by dsyer** [comment]
We long ago decided not to do this, purely in the interests of keeping the codebase as small as possible. While it is certainly an interesting idea, and can be seen as best practice in some situations, blanket use of DTOs for all entities in all settings is probably an anti-pattern. So I don't see any reason to change the decision to keep it simple. Maybe a link to some nice article on DTOs would be useful in the README?
