### ISSUE TITLE
Why don't use the Lombok library?

### ISSUE THREAD

**Issue by coderkan** [spring-projects/spring-petclinic#672]
Hi there,

Using the Lombok library can reduce the writing of getter and setter methods.
Are there any reasons for not using it?

Regards.
Erkan

**Comment by mahdieha** [comment]
Hi dear, 

Thanks for your suggestion.

I strongly agree with you, and this library was recently added to my fork.

You can refer to the following link:
https://github.com/spring-projects/spring-petclinic/pull/673

**Comment by pedsf1968** [comment]
yes @Data

**Comment by ebiggerr** [comment]
Lombok can cause some problems. Moreover, getter and setter methods actually can be auto generated using IDEs, therefore I dont't see that it is a must to use Lombok.

**Comment by bastiat** [comment]
@ebiggerr could you please name these problems?

**Comment by mahdieha** [comment]
> Lombok can cause some problems. Moreover, getter and setter methods actually can be auto generated using IDEs, therefore I dont't see that it is a must to use Lombok.

Hello ebiggerr,

Thank you for your comment.

In fact, this is not about just the magic of any IDE by auto-generated features. In large projects, there is a time limit for each step.

**I draw your attention to my personal experiences:**

1. The magic of @Data creates your getters, setters, toString, and equals/hashcode. Great for DAOs in either the database layer or the API layer, and imagines if you forget one of them = which will cause a bug in the system, and it will still take time to find it.
2. Increases the readability of the code (that I can sacrifice my life for this).
3. Finally, Lombok is used to reduce the boilerplate code for model/data objects.

Do you still think we do not need to speed up writing code effectively?

**Comment by ebiggerr** [comment]
> 
> 
> @ebiggerr could you please name these problems?

Hi. Bastiat. Personally, I think it reduces the readability of the code. But it really depends, some will find it convenient while some who still haven't have fully grasp on the working principles of annotations might having a hard time scratching their head looking at the code. 


>
> 
> Increases the readability of the code (that I can sacrifice my life for this).
Hi, mahdieha. As mentioned above,  statement of "increases the readability" does not fit on my case. 

>
>
> Finally, Lombok is used to reduce the boilerplate code for model/data objects.

Indeed. If Lombok is not used, the classes/project will be full of boilerplate code. For now, it doesn't concern me much as I have not yet step in the industry. ( currently a sophomore).  So, not yet encounter with production env/big projects.

**Comment by snicoll** [comment]
Thanks for the suggestion but we prefer to not use lombok. This is a sample project that newcomers use to get acquainted with Spring and we want them to be able to use the project with a less friction as possible. They shouldn't have to know about lombok and what it does behind the scenes or having to install a plugin in their IDE.
