### ISSUE TITLE
Listing owners triggers N SQL lookups of pet type

### ISSUE THREAD

**Issue by kgilpin** [spring-projects/spring-petclinic#675]
I've been looking at the implementation of Pet Clinic, and in particular [the code that builds the `/owners` list form](https://github.com/spring-petclinic/spring-framework-petclinic/blob/master/src/main/java/org/springframework/samples/petclinic/web/OwnerController.java#L88).

The query efficiently [finds the owners and pets in a single query](https://github.com/spring-petclinic/spring-framework-petclinic/blob/bc38e44e50af94526ea5ca15bfc2ad989b5f0f3b/src/main/java/org/springframework/samples/petclinic/repository/springdatajpa/SpringDataOwnerRepository.java#L35).

However, subsequent to that, multiple queries are issued to obtain the pet type. 

Here is the first of two such queries, shown in context of `processFindForm`:  

<img width="1350" alt="Screen Shot 2020-09-17 at 2 27 47 PM" src="https://user-images.githubusercontent.com/86395/93512238-06518000-f8f2-11ea-9df7-1496b39c88f5.png">

Source: https://app.land/scenarios/56c53af8-6252-4caf-8d9e-04616ae72e4d#timelineBase=8&event=15&filterShow=sql_select%2Csql_insert%2Csql_update%2Cstatic_asset_requests%2Cstack_depth_less&filterShowParams=%7B%22stack_depth_less%22%3A%224%22%7D

It seems desirable to include the pet types in the original query, in order to avoid issuing the two subsequent pet type queries. Is this possible using Spring Data JPA?

**Comment by dsyer** [comment]
I don't know if it's worth it TBH, but it's an interesting question. The issue really is that `PetType` is static data - it's its own `@Entity` for a reason. You can't query all owners or all pets and expect to even find all the available pet types, so I don't immediately see how to fold the `PetType` query in there. We could cache it more aggressively, I suppose.

**Comment by dsyer** [comment]
Not much interest in this, so closing.
