### ISSUE TITLE
Add a prebuilt JAR of the petclinic to a release

### ISSUE THREAD

**Issue by anuraaga** [spring-projects/spring-petclinic#677]
Hello - any thoughts on adding a prebuilt JAR of the petclinic to a GitHub release? It would make it even easier to play with petclinic without needing to build it.

**Comment by snicoll** [comment]
The purpose of this project is to let users get acquainted with Spring with a practical example. As such, I believe that building it is an important step and I expect users to play with the project in an IDE rather than just "using the app".
