### ISSUE TITLE
https required

### ISSUE THREAD

**Issue by Nataliia-Kyr** [spring-projects/spring-petclinic#679]
Hello

I have errors during building project. In logs it is written that it requires https in some links. Can you help me?

Downloaded: https://repo.spring.io/milestone/org/springframework/session/spring-session-bom/Dragonfruit-RELEASE/spring-session-bom-Dragonfruit-RELEASE.pom (3 KB at 6.7 KB/sec)
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.springframework.samples:spring-petclinic:2.3.0.BUILD-SNAPSHOT (/var/jenkins/workspace/Pet_clinic/pom.xml) has 16 errors
[ERROR]     Non-resolvable import POM: Could not transfer artifact com.datastax.oss:java-driver-bom:pom:4.6.1 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/com/datastax/oss/java-driver-bom/4.6.1/java-driver-bom-4.6.1.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2904, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact io.dropwizard.metrics:metrics-bom:pom:4.1.12.1 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/io/dropwizard/metrics/metrics-bom/4.1.12.1/metrics-bom-4.1.12.1.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2911, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.codehaus.groovy:groovy-bom:pom:2.5.13 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/codehaus/groovy/groovy-bom/2.5.13/groovy-bom-2.5.13.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2918, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact com.fasterxml.jackson:jackson-bom:pom:2.11.2 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/com/fasterxml/jackson/jackson-bom/2.11.2/jackson-bom-2.11.2.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2925, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.glassfish.jersey:jersey-bom:pom:2.30.1 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/glassfish/jersey/jersey-bom/2.30.1/jersey-bom-2.30.1.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2932, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.eclipse.jetty:jetty-bom:pom:9.4.31.v20200723 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/eclipse/jetty/jetty-bom/9.4.31.v20200723/jetty-bom-9.4.31.v20200723.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2939, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.junit:junit-bom:pom:5.6.2 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/junit/junit-bom/5.6.2/junit-bom-5.6.2.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2946, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.jetbrains.kotlin:kotlin-bom:pom:1.3.72 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/jetbrains/kotlin/kotlin-bom/1.3.72/kotlin-bom-1.3.72.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2953, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.jetbrains.kotlinx:kotlinx-coroutines-bom:pom:1.3.8 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-coroutines-bom/1.3.8/kotlinx-coroutines-bom-1.3.8.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2960, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact org.apache.logging.log4j:log4j-bom:pom:2.13.3 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/org/apache/logging/log4j/log4j-bom/2.13.3/log4j-bom-2.13.3.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2967, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact io.micrometer:micrometer-bom:pom:1.5.4 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/io/micrometer/micrometer-bom/1.5.4/micrometer-bom-1.5.4.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2974, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact io.netty:netty-bom:pom:4.1.51.Final from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/io/netty/netty-bom/4.1.51.Final/netty-bom-4.1.51.Final.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2981, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact io.r2dbc:r2dbc-bom:pom:Arabba-SR6 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/io/r2dbc/r2dbc-bom/Arabba-SR6/r2dbc-bom-Arabba-SR6.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2988, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact io.projectreactor:reactor-bom:pom:Dysprosium-SR11 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/io/projectreactor/reactor-bom/Dysprosium-SR11/reactor-bom-Dysprosium-SR11.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 2995, column 19 -> [Help 2]
[ERROR]     Non-resolvable import POM: Could not transfer artifact io.rsocket:rsocket-bom:pom:1.0.2 from/to central (http://repo.maven.apache.org/maven2): Failed to transfer file: http://repo.maven.apache.org/maven2/io/rsocket/rsocket-bom/1.0.2/rsocket-bom-1.0.2.pom. Return code is: 501 , ReasonPhrase:HTTPS Required. @ org.springframework.boot:spring-boot-dependencies:2.3.3.RELEASE, /home/jenkins/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.3.3.RELEASE/spring-boot-dependencies-2.3.3.RELEASE.pom, line 3002, column 19 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.junit.jupiter:junit-jupiter-engine:jar is missing. @ line 118, column 17
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by ebiggerr** [comment]
Since January 2020, **The Central Repository**no longer support communication over HTTP. Communication over HTTP will be returned as error. All the 16 errors means that you are trying to download the POMs from **The Central Repository** using HTTP which is definitely gonna rejected.

I'm not sure how you configure the settings. The most straightforward solution is probably changing all the POM import URL pointing to **The Central Repository** to https:// instead of http:// 

Or, if you know the `setting.xml` of your Maven. You can change the `http://repo.maven.apache.org/maven2` to `https://repo.maven.apache.org/maven2`

Hope this helps.

**Comment by Nataliia-Kyr** [comment]
Thank you for answering my question! By the way, solution of the problem was to install newer version of maven.
