### ISSUE TITLE
First letter of "Pet Type" should be capital

### ISSUE THREAD

**Issue by anantjain6** [spring-projects/spring-petclinic#682]
First letter of "Pet Type" should be capital

![](https://user-images.githubusercontent.com/22341750/94831915-eb6f2780-042a-11eb-8ecc-c1ba198cf712.png)

**Comment by somayaj** [comment]
Hi can I contribute? @somayaj is my handle

**Comment by anantjain6** [comment]
@somayaj i have already submitted pull request for it

**Comment by snicoll** [comment]
Thanks for the suggestion @anantjain6.

Closing in favour of PR #683
