### ISSUE TITLE
Change telephone limit to 11.

### ISSUE THREAD

**Issue by Andrew-Rocket** [spring-projects/spring-petclinic#686]
![image](https://user-images.githubusercontent.com/56515695/95678348-d0dc4180-0bd4-11eb-9e11-6412967106fb.png)
Some countries have two-digit country code, so the limit should be 11.

**Comment by pedsf1968** [comment]
10 digits it's only for the phone numbers not for the country code.
4 digits for somes north american countries like Bahamas or Barbade
4+10=14
