### ISSUE TITLE
Implement integration tests

### ISSUE THREAD

**Issue by pedsf1968** [spring-projects/spring-petclinic#692]
I want to add severals unit and  integrations test to improve the code.
It's better to add IT in the java test file name and run them in verify lifecycle.

**Comment by pedsf1968** [comment]
I will implement this part next time

**Comment by dsyer** [comment]
Thank you for your contribution. It would be great to see this in your fork or in the community org (https://github.com/spring-petclinic). We generally don't make such large changes in this, the canonical Pet Clinic.
