### ISSUE TITLE
apache-tomcat-8-perfs/bin/startup.sh: No such file or directory

### ISSUE THREAD

**Issue by eliassal** [spring-projects/spring-petclinic#70]
aged to run the script until the step where it tries to call startup.sh. I see that petclinic.war is copied to apache-tomcat-8-perfs/webapps/Root.war/target but nothing else.
In Jenkins console output I have 

[performanceTest] + /home/salam/TomcatGroovy/apache-tomcat-8-perfs/bin/startup.sh
[performanceTest] /home/salam/jenkins/workspace/workflow.groovy/.1f4e602c/script.sh: line 2: /home/salam/TomcatGroovy/apache-tomcat-8-perfs/bin/startup.sh: No such file or directory

Running: Allocate node : Body : End
Running: Allocate node : End

Question : From where this bin and the script should come from?

Thanks for your help

**Comment by eliassal** [comment]
I have just googled and found an interesting article on deploying web applications to multiple instances of tomcat. So the question now : what is needed to make those 4 directories qaCatalinaBase, stagingCatalinaBase .........what configuration preparation should be done, I would really appreciate if you can point me in the right direction
My box is Fedora 20, nothing is there in /opt, I have the following directories
/var/lib/tomcat/Webapps

/usr/share/tomcat/bin
/usr/share/tomcat/conf (link)
/usr/share/tomcat/lib (link)
/usr/share/tomcat/WebApps (link)

**Comment by michaelisvy** [comment]
Hi,
I don't think this issue has anything to do with Petclinic itself (it is just related to application deployment on Tomcat/Fedora). Please feel free to post to the Tomcat mailing list for that.

Cheers,
Michael.
