### ISSUE TITLE
problem running it on https

### ISSUE THREAD

**Issue by andy-chung** [spring-projects/spring-petclinic#704]
I have deployed it live on 2 sites.
(a) http
http://139.224.231.232
(b) https
https://101.133.236.197

click find owners
click find owner
click andy chung
click add visit
fill in description
click add visit

Doing the same above after final click add visit 
no problem for (a) http. 
But encounter could not connect for (b) https

Appreciate for any help? Thank you.

**Comment by snicoll** [comment]
@andy-chung we can't use this issue tracker for usage question on how to deploy an app with https. Please use stackoverflow for that.
