### ISSUE TITLE
Build failed while running mvn clean install due to ro/isdc/wro/maven/plugin/Wro4jMojo has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0

### ISSUE THREAD

**Issue by Arka-Bandyopadhyay** [spring-projects/spring-petclinic#708]
For java 8 build we have to use <wro4j.version>1.8.0</wro4j.version> not <wro4j.version>1.9.0</wro4j.version> as mentioned in master

**Comment by Arka-Bandyopadhyay** [comment]
added pull request 707

**Comment by Arka-Bandyopadhyay** [comment]
should we close @rstoyanchev  @scothis

**Comment by snicoll** [comment]
@Arka-Bandyopadhyay there is no need to mention individual team members. Issues are triaged when time permits by a member of the team.

**Comment by snicoll** [comment]
Closing in favour of PR #707
