### ISSUE TITLE
'app' container exiting immediately after creating using docker-compose

### ISSUE THREAD

**Issue by gcsumit007** [spring-projects/spring-petclinic#721]
Hi. I am using the docker-compose utility to create the mysql and app services. But after running docker-compose up -d command, mysql container is in up status but app container is in exiting status. 

Please help me troubleshooting this issue.

Thanks,
Sumit

**Comment by dsyer** [comment]
There is no "app" service in the `docker-compose.yml` that ships in this project: it is only used to start the mysql process. If you have a question about running Spring Boot apps in general (not specifically this one), the best place to ask is stackoverflow.
