### ISSUE TITLE
Please notify Windows Users to "git config --global core.autocrlf true" before cloning

### ISSUE THREAD

**Issue by softwareqi** [spring-projects/spring-petclinic#723]
Given the described workflow "Running petclinic locally", this repository won't build properly on a Windows machine and leave the user with questionmarks.

![clrf_problem](https://user-images.githubusercontent.com/68852803/107361750-26b7ec00-6ad8-11eb-8d5f-7b359f1471c9.PNG)

Please notify the User, that before cloning, git needs to be configured to take care of line ending problems.

git config --global core.autocrlf true

**Comment by mimwangi** [comment]
Thanks for the tip. It helped me resolve build errors on Windows 10

**Comment by dsyer** [comment]
Fixed via 8954fa9
