### ISSUE TITLE
java.nio.file.Path cannot be resolved

### ISSUE THREAD

**Issue by fgreg** [spring-projects/spring-petclinic#74]
Cloning this repository and importing into STS results in a compilation error:

The type java.nio.file.Path cannot be resolved. It is indirectly referenced from required .class files

**Comment by fgreg** [comment]
spring-petclinic/src/test/java/org/springframework/samples/petclinic/service/AbstractClinicServiceTests.java line 1

Narrowed this down to the AssertJ library.

AssertJ 2.0 [requires Java 7](http://joel-costigliola.github.io/assertj/assertj-core.html). Currently this project is configured to use Java 6.

Changing the `assertj.version` to 1.7.1 resolves this error.

**Comment by michaelisvy** [comment]
Hi,
we have moved to Java 8 and assertJ 3.0. It's good in my environment. Please let me know in case you still have an issue.
