### ISSUE TITLE
Oracle JDK is needed

### ISSUE THREAD

**Issue by x8a** [spring-projects/spring-petclinic#753]
In the **Prerequisites**, you list `Java 8 or newer` but actually, you need to install Java SE (Oracle JDK) to make it run. Maybe it'd be a good idea to update this prerequisite.

**Comment by lsap** [comment]
Works for me with OpenJDK8u162 from Ubuntu, so I reckon it's not the case.

**Comment by x8a** [comment]
I'm on macOS Big Sur (11.2.3), in case that changes anything.

**Comment by dsyer** [comment]
Did this help: 0d8a80d?

**Comment by x8a** [comment]
Sure, this is better than not having anything. Thanks!
