### ISSUE TITLE
Editing different entities on different tabs

### ISSUE THREAD

**Issue by danipardo** [spring-projects/spring-petclinic#76]
Because the system stores the entity being edited on a SessionAttribute, if I edit two different vets on two different browser tabs, I can update the wrong vet if I post the first form instead of the last one opened.

**Comment by michaelisvy** [comment]
Thanks for pointing this out. 
This is a common problem and you can find an elegant solution to it [here](http://stackoverflow.com/questions/26757128/spring-mvc-sessionattributes-issue-in-multiple-browser-tabs).
Petclinic aims to propose a fairly simple architecture for people who are getting started with Spring so we will not implement that solution.

However, it reminds me that we should probably move our attributes to the request scope instead. This was highlighted by @jdubois a long time ago [here](http://blog.ippon.fr/2013/03/12/improving-the-performance-of-the-spring-petclinic-sample-application-part-2-of-5/). I'll create a separate issue for that.

Cheers,
Michael.
