### ISSUE TITLE
Logs for the API calls

### ISSUE THREAD

**Issue by ganeshmuralidhar** [spring-projects/spring-petclinic#768]
Firstly - Thank you very much for this. Super helpful for beginners like me to start with a Springboot app. 

My request - Are there logs  written for all the API calls? If yes, what is the location and if not, is there a chance to get them added?

**Comment by alexandre-touret** [comment]
Hello @ganeshmuralidhar 
AFAIK, there are no written logs by default for all the API calls in a typical Spring boot app. It could be nice if a Spring developer could confirm ( or the other way around) .

If you want to do that, you can consider :
* [This baeldung article](https://www.baeldung.com/spring-http-logging)
* [A framework such as Logbook](https://github.com/zalando/logbook)

Regards

**Comment by simrin051** [comment]
Hi @alexandre-touret @ganeshmuralidhar 

Is this issue resolved, can i take up this issue

**Comment by simrin051** [comment]
Hi @snicoll / @dsyer / @arey 

Can you please confirm whether i can take up this issue.

**Comment by ganeshmuralidhar** [comment]
@simrin051 Currently I am using` java - jar app.jar > app log.log` to get the logs to a file. But if there can be proper support for log4j and write logs to a file, it will be handy for integrating with systems that have Logs In Context, for example OpenTelemetry or NewRelic or DataDog.

**Comment by dsyer** [comment]
I think it's best practice on most runtimes to stream to stdout. It's kind of a 12 factor principle. So I don't think we should add any more logging configuration to the Pet Clinic.

**Comment by dsyer** [comment]
There aren't really any "API calls" in the vanilla Pet Clinic. I think there is one endpoint but it is never used by the app, so logging calls to it wouldn't help much.
