### ISSUE TITLE
move Session scope attributes to the request scope instead

### ISSUE THREAD

**Issue by michaelisvy** [spring-projects/spring-petclinic#77]
See here:
http://blog.ippon.fr/2013/03/12/improving-the-performance-of-the-spring-petclinic-sample-application-part-2-of-5/

**Comment by arey** [comment]
The JConsole does not show any more session after a JMeter load test:
![no-more-session](https://cloud.githubusercontent.com/assets/838318/10686290/e2914d4e-7962-11e5-9795-b4c4eb7f468b.jpg)
