### ISSUE TITLE
Unable to access JAR File

### ISSUE THREAD

**Issue by farhanahraf03** [spring-projects/spring-petclinic#771]
After executing ./mvnw package on my EC2 instance, I had entered the following command:
java -jar target/*.jar

The output of the command is : Error: Unable to access jarfile target/*.jar

**Comment by snicoll** [comment]
I don't know what would cause this but that seems like a general question, not related to Spring Petclinic. Please ask on StackOverflow.

**Comment by SovietFrontier** [comment]
Anyone find the root issue with this? I am having the same issue. It runs perfectly fine locally but not when being installed on a server with systemd.
