### ISSUE TITLE
Not able to checkout code from master branch

### ISSUE THREAD

**Issue by swamipeddineni** [spring-projects/spring-petclinic#781]
ERROR: Couldn't find any revision to build. Verify the repository and branch configuration for this job.

**Comment by ksackel** [comment]
how are you building it ? azure devops options are completely differnt to those presented in the book.

**Comment by welbsantos** [comment]
Hi, could you please give more details about the issue ?

**Comment by snicoll** [comment]
The name of the branch is `main`.
