### ISSUE TITLE
Build failing due to compatibility issue

### ISSUE THREAD

**Issue by ramkrishnamca** [spring-projects/spring-petclinic#793]
Hi All,

Im running code in AWS linux ec2 machine. when run ./mvnw package, getting below issue. Kindly help

[ERROR] Failed to execute goal io.spring.javaformat:spring-javaformat-maven-plugin:0.0.25:validate (default) on project spring-petclinic: Execution default of goal io.spring.javaformat:spring-javaformat-maven-plugin:0.0.25:validate failed: Unable to load the mojo 'validate' in the plugin 'io.spring.javaformat:spring-javaformat-maven-plugin:0.0.25' due to an API incompatibility: org.codehaus.plexus.component.repository.exception.ComponentLookupException: io/spring/format/maven/ValidateMojo : Unsupported major.minor version 52.0

**Comment by snicoll** [comment]
@ramkrishnamca "Unsupported major.minor version 52.0" has a bunch of hits if you search on Google. For instance, [this SO question](https://stackoverflow.com/questions/10382929/how-to-fix-java-lang-unsupportedclassversionerror-unsupported-major-minor-versi). You need at least Java 8.
