### ISSUE TITLE
Consider moving from Webjars to Bower

### ISSUE THREAD

**Issue by michaelisvy** [spring-projects/spring-petclinic#83]
I think Webjars is a really good option. That being said, I've seen many projects using Bower instead and thought it would be interesting to discuss it.

Cons for Webjars:
* webjars can be confusing for beginners (because it's hard to guess where you should go and find your files)
* webjars relies on Maven. The POM file already is the most verbose config file that we have in Petclinic (and Maven syntax did not "improve" in the past 10 years). So by using webjars we're making it even more verbose. Bower configuration is much more compact because we can declare a dependency in one line like this:
```json
 "dependencies": {
	    "bootstrap": "2.3.0",
	    "jquery": "2.1.3",
  	}
```

Cons for bower
* Node.JS is required if we want to update the dependencies (but not if we simply want to *use* the dependencies)
* I haven't seen a simple way to use it with an internal repository (in the way that Maven does). So all dependencies should be downloaded from the internet directly.
* it uses a JSON file for its configuration. While the JSON format is nice, it does not allow comments.

**Comment by arey** [comment]
I've merged the @faissalwise pull request. To install and execute Spring Petclinic without having Node.JS and Bower installed, I've commited into the vendors directory the third JS librairies petclinic is using.
The ```mvn clean install -Pbower-install``` command line has to be used to update JS librairies.
