### ISSUE TITLE
Petclinic ear not possible to deploy onto latest Weblogic 12.1.3

### ISSUE THREAD

**Issue by davidrehakcz** [spring-projects/spring-petclinic#84]
Hi Gents,
this is more question then issue. Within the Weblogic release notes for version 12.1.3 i have spotted following:
petclinic.ear Does Not Deploy on WebLogic Server
Platform: All
For the SpringSource petclinic sample, the petclinic.war deploys without any problems. The petclinic.ear will not deploy on WebLogic Server because it is not packaged correctly. A request has been sent to SpringSource to fix the petclinic.ear packaging.

Have you yet review this problem? I mean, there is no real explanation what is the problem with the packaging of the ear. Infact, i face similar issue within our project while migrating to WLS 12.1.3. Would appreciate any hint..

Thanks in advance.

**Comment by davidrehakcz** [comment]
So i have found out it was due to the changes to WLST and not tight to the packaging itself.

**Comment by michaelisvy** [comment]
Thanks, good to know it's working now.
