### ISSUE TITLE
Petclinic should be compatible with Java 7 for the time being

### ISSUE THREAD

**Issue by michaelisvy** [spring-projects/spring-petclinic#87]
Petclinic currently requires Java 8 without using any of the Java 8 syntax.

Needed updates:
- move the POM minimum Java version back to Java 7
- Use the diamond operator <> for collections wherever it is relevant.

We will move Petclinic to Java 8 when moving to Spring 5. 
See here for more details: https://spring.io/blog/2015/06/10/feedback-welcome-spring-5-system-requirements

**Comment by arey** [comment]
I think we may close this issue
