### ISSUE TITLE
petclinic.css

### ISSUE THREAD

**Issue by HippieStereo** [spring-projects/spring-petclinic#870]
Hello people ...
I can run the project but css is missing on the repo ...
Layout fragment : <link rel="stylesheet" th:href="@{/resources/css/petclinic.css}" />
Is the project here complete ?
Thanks :-)

**Comment by dsyer** [comment]
Yes, it is complete. You have to run a build on the command line, or from your IDE with Maven to generate the CSS.

UPDATE: in #868 we made the decision to commit CSS to source code and put the generation configuration behind a profile.

**Comment by HippieStereo** [comment]
> 

Hi Dave.
Thanks a lot ... it was a quick and very helpful response.
It work good thank you again : cheers from Portugal :-)
