### ISSUE TITLE
Question about "Cannot resolve" in html files (question)

### ISSUE THREAD

**Issue by elfiorr** [spring-projects/spring-petclinic#875]
Hi, 

For example in ownersList.html file i have many red underlines on fields/getters. What should I import to resolve that, because Intellij don't know what is this. 

Thanks for response,
Regards

**Comment by dsyer** [comment]
Maybe it depends on the IDE and tools you have installed. I don't see such markers in Eclipse or VSCode, but I haven't attempted to install any Thymeleaf extensions in either case. I doubt this is anything to do with the source code.
