### ISSUE TITLE
Formatting violations found in the following files:

### ISSUE THREAD

**Issue by murt30** [spring-projects/spring-petclinic#908]
Failed to execute goal io.spring.javaformat:spring-javaformat-maven-plugin:0.0.25:validate (default) on project spring-petclinic: Formatting violations found in the following files:
.jenkins\workspace\petclinicTest\src\main\java\org\springframework\samples\petclinic\model\BaseEntity.java
.jenkins\workspace\petclinicTest\src\main\java\org\springframework\samples\petclinic\model\NamedEntity.java
etc

**Comment by dsyer** [comment]
There is no `.jenkins` in the source code for this project. I guess you need to find where that came from and address the issue there?

**Comment by murt30** [comment]
Thanks Dave,
 I had to add a spring-javaformat:apply tag to the maven goal and it worked.
Murt
