### ISSUE TITLE
Consider adding pagination to list views

### ISSUE THREAD

**Issue by eustachef** [spring-projects/spring-petclinic#91]
Most real app will need pagination I guess, so it would be nice to have prototypical implementation.

**Comment by liouxiao** [comment]
According to http://dandelion.github.io/components/datatables/1.1.0/docs/html/#4-2-feature-enablement, `dandelion-datatales` already supports pagination, and you'd turn on this feature by simply setting `pageable` attribute to true in related jsp files (e.g. `ownerList.jsp`), like this:

```
    <datatables:table id="owners" data="${selections}" row="owner" theme="bootstrap2" 
                      cssClass="table table-striped" pageable="true" info="false" export="pdf">
```

**Comment by arey** [comment]
For large dataset (this in mostly the case in real application), server side pagination is the best. We may use dandelion pagination support. But DAO have also to be updated.

**Comment by somayaj** [comment]
hi, can this be worked on?

**Comment by simrin051** [comment]
Hi @arey @somayaj  

Can i take up this issue

**Comment by arey** [comment]
@simrin051, I think so but we may ask confirmation to @snicoll or @dsyer

**Comment by simrin051** [comment]
Hi @snicoll / @dsyer 

Can you please confirm whether i can take up this issue

**Comment by simrin051** [comment]
Hi @arey

I have commented on the API logs issue. Can you please confirm.

**Comment by dsyer** [comment]
I don't see the connection with the logs issue. If you want to make a proposal for pagination, go ahead. I think I would prefer to see something that didn't use additional libraries, but I guess we can assess that when we have something to look at. Pet Clinic has no Javascript in the web layer, and that does enable us to concentrate on the Spring side of things and not get caught up in JS dependency churn. Ideally we'd keep it that way IMO, but we can keep the options open while there is no code to review..

**Comment by simrin051** [comment]
Thanks @dsyer  i will take up this issue
