### ISSUE TITLE
fail to run test in maven

### ISSUE THREAD

**Issue by MikeZheng** [spring-projects/spring-petclinic#92]
I encountered an issue that description is "org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [SELECT id as visit_id, visit_date, description FROM visits WHERE pet_id=?]; SQL state [S0022]; error code [0]; Column 'visits.id' not found.; nested exception is java.sql.SQLException: Column 'visits.id' not found." when running test in maven.

I use MySQL as database.
![petclinic-issue](https://cloud.githubusercontent.com/assets/8818456/9292989/bde3b08e-4449-11e5-845c-a8ac7c7d5bb2.jpg)

I think the root cause is that the sql in method "findByPetId" of class JdbcVisitRepositoryImpl are not mapped with the method "mapRow" of class JdbcVisitRowMapper.

**Comment by arey** [comment]
Hi MikeZheng, could you please pull the last commit and execute your test again?
