### ISSUE TITLE
Changing owner information makes their pets disappear

### ISSUE THREAD

**Issue by OlianasD** [spring-projects/spring-petclinic#947]
When we change some information of an owner, their pets disappear from the PetClinic app. Tested on Windows 10, Java version 14.0.2, with both the integrated H2 database and MySQL.

Steps to reproduce:
Steps to reproduce:
-connect to the app -> Find owners -> Find owner
-George Franklin -> Edit owner
-set a new first name for the owner
-after clicking Update, the app shows the owner information page without the pets

**Comment by dsyer** [comment]
Fixed in d381fb6
