### ISSUE TITLE
command ./mvnw package failing

### ISSUE THREAD

**Issue by anshul17024** [spring-projects/spring-petclinic#980]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/40620896/171396664-199acb20-9f6c-4243-97ec-99c27927b9a8.png">

[ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.springframework.samples:spring-petclinic:2.7.0-SNAPSHOT: Could not transfer artifact org.springframework.boot:spring-boot-starter-parent:pom:2.7.0 from/to central (https://artifactory.oci.oraclecorp.com/libs-release): transfer failed for https://artifactory.oci.oraclecorp.com/libs-release/org/springframework/boot/spring-boot-starter-parent/2.7.0/spring-boot-starter-parent-2.7.0.pom and 'parent.relativePath' points at wrong local POM @ line 8, column 11

**Comment by anshul17024** [comment]
@snicoll @arey @dsyer Please help. 
I tried using both java 8 and java 11, it is failing and giving same output in both.
Thank you.

**Comment by snicoll** [comment]
@anshul17024 please don't ping individual contributors like that. There is a host to oraclecorp.com in that screenshot that should be related to your environment. If you have trouble using Maven, please ask on StackOverflow.

**Comment by anshul17024** [comment]
Thanks, I used my company's vpn and then ran the command, it worked.
