### ISSUE TITLE
Remove lastName method param where unused in OwnerController

### ISSUE THREAD

**Issue by kvaithin** [spring-projects/spring-petclinic#985]
The `addPaginationModel` private method inside the `OwnerController` class takes in the `lastName` parameter but doesn't use it to set the model attribute. Would we want to update this? Or remove this param. Could add a PR on this. 

https://github.com/spring-projects/spring-petclinic/blob/main/src/main/java/org/springframework/samples/petclinic/owner/OwnerController.java#L118

**Comment by dsyer** [comment]
A PR would be welcome thanks. There's a redundant local variable assignment as well if you're feeling tidy.

**Comment by dsyer** [comment]
Fixed via #985
