### ISSUE TITLE
Maven HTTP error for jaxb dependency

### ISSUE THREAD

**Issue by dave-kennedy** [spring-projects/spring-petclinic#996]
Using OpenJDK 16 on Alpine 3.13 and running `./mvnw dependency:go-offline` results in the following error:

```
Downloaded from central: https://repo.maven.apache.org/maven2/org/ehcache/ehcache/3.10.0/ehcache-3.10.0.jar (1.8 MB at 3.1 MB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:01 min
[INFO] Finished at: 2022-06-17T19:59:09Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.3.0:go-offline (default-cli) on project spring-petclinic: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.ehcache:ehcache:jar:3.10.0 -> org.glassfish.jaxb:jaxb-runtime:jar:2.3.0-b170127.1453 -> org.glassfish.jaxb:jaxb-core:jar:2.3.0-b170127.1453 -> javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Failed to read artifact descriptor for javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Could not transfer artifact javax.xml.bind:jaxb-api:pom:2.3.0-b161121.1438 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [releases.java.net (http://maven.java.net/content/repositories/releases/, default, releases+snapshots), shapshots.java.net (http://maven.java.net/content/repositories/snapshots/, default, releases+snapshots), jvnet-nexus-staging (http://maven.java.net/content/repositories/staging/, default, releases+snapshots), netbeans (http://bits.netbeans.org/nexus/content/groups/netbeans, default, releases)] -> [Help 1]
```

I found a workaround on [SO](https://stackoverflow.com/questions/67001968/how-to-disable-maven-blocking-external-http-repositories).

1. Create .mvn/maven.config with the following:

       --settings ./.mvn/local-settings.xml

2. Create .mvn/local-settings.xml with the following:

       <settings xmlns="https://maven.apache.org/SETTINGS/1.2.0"
                 xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="https://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
           <mirrors>
               <mirror>
                   <id>releases.java.net.ssl</id>
                   <mirrorOf>releases.java.net</mirrorOf>
                   <name></name>
                   <url>https://maven.java.net/content/repositories/releases/</url>
               </mirror>
               <mirror>
                   <id>shapshots.java.net.ssl</id>
                   <mirrorOf>shapshots.java.net</mirrorOf>
                   <name></name>
                   <url>https://maven.java.net/content/repositories/snapshots/</url>
               </mirror>
               <mirror>
                   <id>jvnet-nexus-staging-ssl</id>
                   <mirrorOf>jvnet-nexus-staging</mirrorOf>
                   <name></name>
                   <url>https://maven.java.net/content/repositories/staging/</url>
               </mirror>
               <mirror>
                   <id>netbeans-ssl</id>
                   <mirrorOf>netbeans</mirrorOf>
                   <name></name>
                   <url>https://netbeans.apidesign.org/maven2/</url>
               </mirror>
           </mirrors>
       </settings>

**Comment by zhucucao** [comment]
> Using OpenJDK 16 on Alpine 3.13 and running `./mvnw dependency:go-offline` results in the following error:
> 
> ```
> Downloaded from central: https://repo.maven.apache.org/maven2/org/ehcache/ehcache/3.10.0/ehcache-3.10.0.jar (1.8 MB at 3.1 MB/s)
> [INFO] ------------------------------------------------------------------------
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  05:01 min
> [INFO] Finished at: 2022-06-17T19:59:09Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.3.0:go-offline (default-cli) on project spring-petclinic: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.ehcache:ehcache:jar:3.10.0 -> org.glassfish.jaxb:jaxb-runtime:jar:2.3.0-b170127.1453 -> org.glassfish.jaxb:jaxb-core:jar:2.3.0-b170127.1453 -> javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Failed to read artifact descriptor for javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Could not transfer artifact javax.xml.bind:jaxb-api:pom:2.3.0-b161121.1438 from/to maven-default-http-blocker (http://0.0.0.0/): Blocked mirror for repositories: [releases.java.net (http://maven.java.net/content/repositories/releases/, default, releases+snapshots), shapshots.java.net (http://maven.java.net/content/repositories/snapshots/, default, releases+snapshots), jvnet-nexus-staging (http://maven.java.net/content/repositories/staging/, default, releases+snapshots), netbeans (http://bits.netbeans.org/nexus/content/groups/netbeans, default, releases)] -> [Help 1]
> ```
> 
> I found a workaround on [SO](https://stackoverflow.com/questions/67001968/how-to-disable-maven-blocking-external-http-repositories).
> 
> 1. Create .mvn/maven.config with the following:
>    ```
>    --settings ./.mvn/local-settings.xml
>    ```
> 2. Create .mvn/local-settings.xml with the following:
>    ```
>    <settings xmlns="https://maven.apache.org/SETTINGS/1.2.0"
>              xmlns:xsi="https://www.w3.org/2001/XMLSchema-instance"
>              xsi:schemaLocation="https://maven.apache.org/SETTINGS/1.2.0 https://maven.apache.org/xsd/settings-1.2.0.xsd">
>        <mirrors>
>            <mirror>
>                <id>releases.java.net.ssl</id>
>                <mirrorOf>releases.java.net</mirrorOf>
>                <name></name>
>                <url>https://maven.java.net/content/repositories/releases/</url>
>            </mirror>
>            <mirror>
>                <id>shapshots.java.net.ssl</id>
>                <mirrorOf>shapshots.java.net</mirrorOf>
>                <name></name>
>                <url>https://maven.java.net/content/repositories/snapshots/</url>
>            </mirror>
>            <mirror>
>                <id>jvnet-nexus-staging-ssl</id>
>                <mirrorOf>jvnet-nexus-staging</mirrorOf>
>                <name></name>
>                <url>https://maven.java.net/content/repositories/staging/</url>
>            </mirror>
>            <mirror>
>                <id>netbeans-ssl</id>
>                <mirrorOf>netbeans</mirrorOf>
>                <name></name>
>                <url>https://netbeans.apidesign.org/maven2/</url>
>            </mirror>
>        </mirrors>
>    </settings>
>    ```

same problem.But this is not use for me.

**Comment by jashburn8020** [comment]
Applying @dave-kennedy 's workaround results in the following:

```
Downloaded from central: https://repo.maven.apache.org/maven2/org/ehcache/ehcache/3.10.0/ehcache-3.10.0.jar (1.8 MB at 4.9 MB/s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  06:23 min
[INFO] Finished at: 2022-08-04T01:21:25Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.3.0:go-offline (default-cli) on project spring-petclinic: org.eclipse.aether.resolution.DependencyResolutionException: Failed to collect dependencies at org.ehcache:ehcache:jar:3.10.0 -> org.glassfish.jaxb:jaxb-runtime:jar:2.3.0-b170127.1453 -> org.glassfish.jaxb:jaxb-core:jar:2.3.0-b170127.1453 -> javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Failed to read artifact descriptor for javax.xml.bind:jaxb-api:jar:2.3.0-b161121.1438: Could not transfer artifact javax.xml.bind:jaxb-api:pom:2.3.0-b161121.1438 from/to netbeans-ssl (https://netbeans.apidesign.org/maven2/): transfer failed for https://netbeans.apidesign.org/maven2/javax/xml/bind/jaxb-api/2.3.0-b161121.1438/jaxb-api-2.3.0-b161121.1438.pom: Unknown host netbeans.apidesign.org: Try again -> [Help 1]
```

The problem is https://netbeans.apidesign.org/maven2/javax/xml/bind/jaxb-api/2.3.0-b161121.1438/jaxb-api-2.3.0-b161121.1438.pom returns a 404. Finding a solution for this...

**Comment by jashburn8020** [comment]
This further workaround seems to work - by adding the following to `pom.xml` as suggested in [SO](https://stackoverflow.com/a/72150668). It avoids the use of jaxb-api-2.3.0-b161121.1438.

```xml
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>javax.xml.bind</groupId>
        <artifactId>jaxb-api</artifactId>
        <version>2.3.1</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

**Comment by dsyer** [comment]
Works for me with Java 17. Assume this is obsolete.
